### ISSUE TITLE
Deploying the ACE+MQ docker image on Openshift 

### ISSUE THREAD

**Issue by rudra108** [ot4i/ace-docker#101]
I need to deploy the ACE+MQ docker image on a managed openshift cluster (RHMI). IBM provides helm charts for deployment on Openshift but that is supported by Openshift dedicated only. I need to do this on managed cluster which doesn't support helm 2 charts.

https://github.com/IBM/charts/tree/master/stable/ibm-ace-server-dev

IBM hasn't yet provided the openshift or Kubernetes templates that is supported by Openshift managed. I need some help.

**Comment by IBMRob** [comment]
Unfortunately there are no OpenShift templates for deploying these images but there is a blog on how to deploy the images natively - https://developer.ibm.com/integration/blog/2018/12/19/app-connect-enterprise-v11-for-ibm-cloud-private-on-red-hat-openshift/
The strategic direction has been to deploy using helm. Its possible to install helm even into managed clusters using https://blog.openshift.com/getting-started-helm-openshift/. Helm also supports being installed into a single namespace. In the future we would be looking to move to operators to deploy these images although there is no ETA.

**Comment by rudra108** [comment]
Thanks for clarifying.
