### ISSUE TITLE
Dockerfile.acemq: microdnf install --nodocs causes non-zero return code

### ISSUE THREAD

**Issue by tchan-sharedhealth** [ot4i/ace-docker#102]
When I was trying to run the following command, 

docker build -t ace-mq --build-arg BASE_IMAGE=MQ-9.1.4-amd64 --build-arg ACE_INSTALL=11.0.0-ACE-LINUXX64-FP0007.tar.gz --file ubi/Dockerfile.acemq .

I got this exception

Running transaction test...
The command '/bin/sh -c microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all' returned a non-zero code: 141

I googled this return code, and someone suggested that the issue is with the "--nodocs" in the "RUN microdnf install" command in line 60 in the Dockerfile.acemq.  See https://github.com/rpm-software-management/microdnf/issues/50

After I removed the "--nodocs" from the command, I was able to successfully build the image. My question is, is this a proper way of fixing the build?

**Comment by IBMRob** [comment]
This change has been pushed to all our files with the latest release 👍
