### ISSUE TITLE
log4j pluggin setup in ACE Openshift

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#104]
Hi Team,

I am working on Log4j setup with ACE 11.0.0.5 in openshift. I tried to place log4j jars in /home/aceuser/shared-classes dir. but it doesn't work. so tried to copy jars under "/home/aceuser/ace-server/config/components/integration_server/servers/ACEIS" then it work.but challenge is ACEIS folder get created only when ACE Integration Server is running. So I need to understand how can i copy jars in image once ACE IS is UP.

**Comment by atulsingh0** [comment]
Place that jar into /home/aceuser/ace-server/shared-classes, it will work

**Comment by IBMRob** [comment]
Answered by @atulsingh0
