### ISSUE TITLE
Clarification request on topic 'How to dynamically configure the ACE Integration Server'

### ISSUE THREAD

**Issue by OmBabosa** [ot4i/ace-docker#105]
Hi,

The section states 'Before the Integration Server starts, the container is checked for the folder /home/aceuser/initial-config. For each folder in /home/aceuser/initial-config a script called ace_config_{folder-name}.sh will be run to process the information in the folder.'

Could you please clarify the below:
a) Is there a particular order in which the scripts 'ace_config_{folder-name}.sh' are called? Say, i have these five sub-directories inside the /home/aceuser/initial-config' - bars, policy, odbcini, sapjcolib & setdbparms. I am actually looking to add a new sub-directory, say 'userscript', and wants this to get executed only after the all the other sub-directory content is processed.
b) What would be your suggest to handle the environment specific details, like the connection details that vary across environment (the policies, the setdbparms etc)? i want to make use of the Kubernetes ConfigMap to influence values for such environment fields in the policies etc.

Thanks in advance for your help!

**Comment by IBMRob** [comment]
a) Currently there is no predictive order to the folders being scanned. Its the order the go code gets them back in (which from experience can vary). You can see the code doing the scanning at https://github.com/ot4i/ace-docker/blob/0b759fc51c9836a5b201c6b7bf06569045fbc6e1/cmd/runaceserver/integrationserver.go#L66. We are open to PRs to improve this to make the order predictable. 
b) When this container is used with helm charts we use secrets to store all the configuration and then mount them into the folders under `initial-config`, this means all the environment values can be changes without changing the image/bar file

If

**Comment by OmBabosa** [comment]
Thank you very much for your response Rob - we are exploring the option to use helm charts as you had advised. Will get back to you as required in a couple of days time. Thanks again!
