### ISSUE TITLE
How to install ksh into ace-mq container ?

### ISSUE THREAD

**Issue by vietph83** [ot4i/ace-docker#109]
Hi support team

I need help on how to install ksh into ace-mq (latest) which is built based on ubi7 image

I did try install ksh using command in ace-mq container

`microdnf install ksh`

I got error telling me that there is no package name 'ksh'

**Comment by IBMRob** [comment]
`ksh` is likely part of another package. You should be able to use `dnf provides '*filename'` to find which package it belongs to and needs to be installed.

**Comment by vietph83** [comment]
Hi IBMRob

I tried this in the ace-mq container

```
bash-4.4$ dnf
bash: dnf: command not found
```

**Comment by IBMRob** [comment]
I suggest using a redhat docker container to find what package `ksh` is part of.

**Comment by vietph83** [comment]
Thank you for your feedback on this IBMRob
I will give it a try later
