### ISSUE TITLE
DB2 and MS SQL drivers for ACE on CP4I + example in odbc.ini

### ISSUE THREAD

**Issue by abudavis** [ot4i/ace-docker#110]
We are using ACE on CP4I and can see that you do not by default have an ACE image with a DB2 driver in it to connect to DB2. Ideally I would expect to see this under "/opt/ibm/ace-11/server/ODBC/drivers/lib"

Also, could you please make an example configuration to connect to DB2 and MS SQL DB in the provided sample? - https://github.com/ot4i/ace-docker/tree/master/sample/initial-config/odbcini

**Comment by IBMRob** [comment]
Hi - You'r right, we have not got a sample dockerfile/image that includes the DB2 drivers in it. This is something on our roadmap but currently no ETA. 

Regarding example odic.ini files. You should be able to use the ACE documentation - https://www.ibm.com/support/knowledgecenter/SSTTDS_11.0.0/com.ibm.etools.mft.doc/bk58060_.html to generate the require files.

**Comment by abudavis** [comment]
Thank you. If we were to bake our own docker image, which version of DB2 client (and its ODBC driver) would you recommend so that we could connect to our database platform on DB2/400?

**Comment by IBMRob** [comment]
You would need to use the appropriate version that is supported by both ACE and your end system
