### ISSUE TITLE
mqsiapplybaroverride on ACE on CP4I

### ISSUE THREAD

**Issue by abudavis** [ot4i/ace-docker#111]
Hello
Just like the custom server.conf.yaml, setdbparms, etc., was wondering if there is any way to have the ACE instance run a "mqsiapplybaroverride" on the bar file in /home/aceuser/initial-config/bars before the modified bar file is deployed by the integration server?

Environment: ACE on CP4I
Version: Latest

**Comment by IBMRob** [comment]
You could create a new init script which processed overrides that were defined in a subfolder i.e.  `https://github.com/ot4i/ace-docker/blob/master/ace_config_applybaroverride.sh`
and it would apply any overrides that were in `/home/aceuser/initial-config/applybaroverride`

You would need to come up with a format of what was in the files and how they were processed.

**Comment by abudavis** [comment]
On CP4I, on an ACE pod, I can see the following directories inside /home/aceuser/initial-config
"agent  bars  extensions  odbcini  policy  serverconf  setdbparms  ssl"

If I now place an odbc.ini inside /home/aceuser/initial-config/odbcini, the on startup of pod, it would automatically pick up and deploy the configuration is my understanding, is that correct?

Based on the above context, did you mean that I could create a script "ace_config_applybaroverride.sh" and place it (say)  and create a "applybaroverride" folder under /home/aceuser/initial-config/ (as I do not see that on the integration server pod) and place ace_config_applybaroverride.sh and the .properties file and ace should pick it up on startup?

**Comment by IBMRob** [comment]
On startup the go code will look inside the ` /home/aceuser/initial-config/` folder. For any folder it finds, it will run the script with the name `ace_config_<subfolder-name>.sh`.

i.e. you would put a file called `overrides` in the folder `/home/aceuser/initial-config/applybaroverride`. Inside that file you would put all the overrides you want to do. 
You would then create a file called `ace_config_applybaroverride.sh`which inside knew how to process the data you have put it in the `overrides` file and apply the overrides to the appropriate bar file. 

There is nothing built into ACE to perform this. You need to create the logic to know which bar to override, what values etc.

**Comment by abudavis** [comment]
This is great!
1) The "overrides" file can it take any other name such as "params.properties"?
2) What is the sequence in which the folders are checked on startup? Logically speaking, it should first check the folder "/home/aceuser/initial-config/applybaroverride" BEFORE checking "/home/aceuser/initial-config/bars" because the "ace_config_applybaroverride.sh" script we make will create an updated barfile in "/home/aceuser/initial-config/bars" and as such if the "bars" directory is checked first, then it would be empty!

**Comment by IBMRob** [comment]
1) The name and contents of the new file is completely down how you code the script that parses it. 
2) Slight sticking point here - Currently the code will run the scripts in a random order (well its not totally random, the go get s directly listing and then processes them in that order so it is subject to change).  If you need to perform the bar override before the bars are processed then the code will need to be updated to to always process the orders in a defined order. Probably the easiest short term fix would be to update https://github.ibm.com/Cloud-Integration/ot4i-ace-docker/blob/master/cmd/runaceserver/integrationserver.go#L91 so that it sorts `fileList`

**Comment by abudavis** [comment]
Tried the link, its asking for IBM W3 credentials, IBM internal git?

**Comment by IBMRob** [comment]
Fixed the link

**Comment by abudavis** [comment]
Still the same :(

**Comment by IBMRob** [comment]
Maybe your browser has cached it. You should be able to navigate to the updated url.

**Comment by abudavis** [comment]
Nope, have now tried 3 browsers and on a cellphone :(

**Comment by nasroht** [comment]
Same here, i get the w3c login. And I didn’t try it earlier.
