### ISSUE TITLE
MS SQL JDBC database driver missing on ACE on CP4I?

### ISSUE THREAD

**Issue by abudavis** [ot4i/ace-docker#112]
Wondering if the MS SQL JDBC database driver is missing on ACE on CP4I!?
The intent is to connect to MQ SQL Database using the JDBCProviders policy (JDBC type 4) to read and write to tables, the policy xml is below.

Get the following error in the logs on ACE 11.0.0.8 on CP4I 2019.4.1

`2020-04-01 15:10:09.395338: An error occurred in node: Broker 'integration_server'; Execution Group 'xxxx'; Message Flow 'xxxxx'; Node 'Insert to DB'; Node Type 'xxxx_JavaCompute There was a problem establishing a connection to the given database URL: jdbc:sqlserver://DB01.redacted.com\Industriell:1433;DatabaseName=IIBDB;user=user;password=redacted Exception details:   error message: No suitable driver, SQLState value: 08001, stack trace: [com.ibm.broker.jdbctype4.jdbcdbasemgr.JDBCType4Connection.createNonXAConnection(JDBCType4Connection.java:466)
2020-04-01 15:10:10.401017: An error occurred in node: Insert to DB There was a problem establishing a connection to the given database URL: datasource URL = jdbc:sqlserver://DB01.redacted.com\ns:1433;DatabaseName=IIBDB;user=user;password=redacted Exception details: No suitable drive `

Policy xml:
`<?xml version="1.0" encoding="UTF-8"?>
<policies>
  <policy policyType="JDBCProviders" policyName="jdbcproviderspolicy001" policyTemplate="Microsoft SQL Server">
    <databaseName>IIBDB</databaseName>
    <databaseType>Microsoft SQL Server</databaseType>
    <databaseVersion></databaseVersion>
    <type4DriverClassName>com.microsoft.sqlserver.jdbc.SQLServerDriver</type4DriverClassName>
    <type4DatasourceClassName>com.microsoft.sqlserver.jdbc.SQLServerXADataSource</type4DatasourceClassName>
    <connectionUrlFormat>jdbc:sqlserver://DB01.redacted.com\ns:1433;DatabaseName=IIBDB;user=user;password=redacted</connectionUrlFormat>
    <connectionUrlFormatAttr1></connectionUrlFormatAttr1>
    <connectionUrlFormatAttr2></connectionUrlFormatAttr2>
    <connectionUrlFormatAttr3></connectionUrlFormatAttr3>
    <connectionUrlFormatAttr4></connectionUrlFormatAttr4>
    <connectionUrlFormatAttr5></connectionUrlFormatAttr5>
    <serverName>DB01.redacted.com</serverName>
    <portNumber>1433</portNumber>
    <jarsURL>/opt/ibm/ace-11/server/adapters/prereqs/jars</jarsURL>
    <databaseSchemaNames>useProvidedSchemaNames</databaseSchemaNames>
    <description></description>
    <maxConnectionPoolSize>0</maxConnectionPoolSize>
    <securityIdentity>myjdbcsecid</securityIdentity>
    <environmentParms></environmentParms>
    <jdbcProviderXASupport>false</jdbcProviderXASupport>
    <useDeployedJars>false</useDeployedJars>
  </policy>
</policies>`

**Comment by IBMRob** [comment]
IBM does not ship JDBC drivers in the ACE product. You need to supply these either by baking them into the image or by putting them into the bar file and indicating such in your jdbc policy

**Comment by abudavis** [comment]
@IBMRob Thank you!
