### ISSUE TITLE
Mqsichangeflowmonitoring command is not being executed 

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#113]
Hi Rob,
When we are trying to run mqsichangeflowmonitoring command in ace MQ container getting below error - 

`sh-4.2$ mqsichangeflowmonitoring -i localhost -p 7600 -k Rest_ENotification -f Rest_ENotification -m {ProjPolicy}:Monitoring -c active`

BIP8139E: The user issuing this command does not have the required permissions to execute the command.

BIP8039E: The integration server is not available.

The integration server could not be found; it may have been deleted by the App Connect Enterprise Toolkit or a custom integration application.
Use the App Connect Enterprise Toolkit or a custom integration application to see if the integration server exists.`

**Comment by IBMRob** [comment]
How are you running the container? Have you setup security on the web admin port?

If I create a simple container by running `docker run --name acemqserver -p 7600:7600 -p 7800:7800 -p 7843:7843 -p 1414:1414 --env LICENSE=accept --env MQ_QMGR_NAME=QMGR --env ACE_SERVER_NAME=ACESERVER ibmcom/ace-mq` I can then exec into the container and the command appears to work 
```
bash-4.4$ . /opt/ibm/ace-11/server/bin/mqsiprofile

MQSI 11.0.0.8
/opt/ibm/ace-11/server

bash-4.4$ mqsichangeflowmonitoring -i localhost -p 7600 -k Rest_ENotification -f Rest_ENotification -m {ProjPolicy}:Monitoring -c active
BIP8279E: The application is not available. 
The application could not be found; it may have been deleted by the App Connect Enterprise Toolkit or a custom integration application. 
Use the App Connect Enterprise Toolkit or a custom integration application to see if the application exists. 
```

The error returned is because that app isn't deployed to the server.

**Comment by atulsingh0** [comment]
Yes, web UI credentials are been setup

**Comment by IBMRob** [comment]
From a colleague

> If you want to connect to a secured integration node or server as a specific user, provide the security credentials as a URI in the following format: tcp://user:password@hostname. If your password contains URI Reserved characters, you must convert these characters to the percent-encoded format. For more information, see A correct URL and password returns error BIP1939 when you attempt to connect to a remote host name in Resolving problems when running commands.

**Comment by atulsingh0** [comment]
Thanks, I will try that. Meanwhile, we are also seeing below error which is continuous in standard output, seems like this also belongs to same - 

```
2020-04-03T18:02:13.130Z Can't tell if ace admin server security is enabled defaulting to false
2020-04-03T18:02:13.130Z Connecting to ws://localhost:7600/ for statistics
2020-04-03T18:02:13.144Z Connecting to ws://localhost:7600/ without using session cookie
2020-04-03T18:02:13.145Z Error calling ace admin server webservice endpoint unexpected EOF
2020-04-03T18:02:13.146Z Connecting to ws://localhost:7600/ for statistics
2020-04-03T18:02:13.149Z Connecting to ws://localhost:7600/ without using session cookie
2020-04-03T18:02:13.150Z Error calling ace admin server webservice endpoint unexpected EOF
```

**Comment by atulsingh0** [comment]
@IBMRob how can we put monitoring command in config scripts, I have tried the same but cmds throws the error that integration server is not ready. 
Is there a way to auto run monitoring commands for services?

**Comment by IBMRob** [comment]
@atulsingh0 - Have you enabled webstats on the env. `MQ_ENABLE_METRICS=true` ? 

If you log into the WebUI are you able to see WebStats?

**Comment by atulsingh0** [comment]
Yes, I am able to see them

**Comment by IBMRob** [comment]
What customisation have you done to the container?

**Comment by atulsingh0** [comment]
- We have added our certs in image
- adding Initial load file set
- Put shared-classes config script
- We have custom monitoring profile which is working fine in IIB, we have used the same monitoring profile here as well

But we have to enable the properties on flows manually

**Comment by IBMRob** [comment]
The mentioned changes shouldn't affect accounts and stats working. I would suggest disabling each change in term to detect what change broke the capability.

**Comment by atulsingh0** [comment]
Do you think, if we have a custom monitoring profile, we have to run mqsichange property manually? Can’t we automate this?

**Comment by atulsingh0** [comment]
@IBMRob can you please open this issue, I’ve closed it by mistake

**Comment by IBMRob** [comment]
If you have enabled SSL on metrics then you need to add some extra configuration. If you look at https://github.com/ot4i/ace-docker/blob/master/internal/metrics/update.go#L101 you will be able to see the extra Env vars that are required, specially,

ACE_ADMIN_SERVER_SECURITY, ACE_ADMIN_SERVER_CA, ACE_ADMIN_SERVER_CERT, ACE_ADMIN_SERVER_KEY

**Comment by atulsingh0** [comment]
Helm chart for v11.0.0.8 template does not have these env variables

**Comment by IBMRob** [comment]
Yes you will need to update the chart to supply these values

**Comment by atulsingh0** [comment]
Ok, let me try that

**Comment by atulsingh0** [comment]
Weirdly, I have used ‘adminServerSecure : false’ and removed the web users still I can see above errors?

Any idea, why?

**Comment by IBMRob** [comment]
This repo has been updated to provide a new ACE image. If you think this issue is still applicable please re-open. 

For general ACE enquiries please use  https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?communitykey=77544459-9fda-40da-ae0b-fc8c76f0ce18
