### ISSUE TITLE
Message flow says Keystore is missing in ACE on CP4I

### ISSUE THREAD

**Issue by abudavis** [ot4i/ace-docker#115]
ACE reports "No keystore configured" error in a message flow in ACE 11.0.0.8 on CP4I 2019.4.1.

As a pre-requisite for ACE pod to create the keystore, the generateSecret.sh was run (against the keystore-testace.crt, keystore-testace.key, keystore-testace.pass, keystorePassword.txt) which is included as part of the IBM provided helm chart for ACE for CP4I where "testace" is the keystore key alias name.(https://raw.githubusercontent.com/IBM/charts/master/repo/entitled/ibm-ace-server-icp4i-prod-3.0.0.tgz). 

Helm install params used [--set integrationServer.configurationSecret=secret-created-in-openshift-by-generatesecret-sh] & [integrationServer.keystoreKeyNames=testace]

Not sure if ACE on CP4I requires an HTTPS listener to be setup like IIB? - https://www.ibm.com/support/knowledgecenter/SSMKHH_9.0.0/com.ibm.etools.mft.doc/ap12234_.htm

```
--ACE folder structure inside pod--
sh-4.2$ pwd
/home/aceuser/ace-server
sh-4.2$ ls -ltr
total 48
-rw-r--r--. 1 aceuser aceuser 38732 Mar 19 15:53 server.conf.yaml
-rw-r--r--. 1 aceuser aceuser 3060 Apr 16 18:38 keystore.jks
-rw-r--r--. 1 aceuser aceuser 1839 Apr 16 18:38 odbc.ini
drwxr-xr-x. 2 aceuser aceuser   6 Apr 16 18:38 ssl
drwxrwxr-x. 1 aceuser aceuser  53 Apr 16 18:38 overrides
drwxrwxr-x. 1 aceuser aceuser  96 Apr 16 18:38 log
drwxrwxr-x. 1 aceuser aceuser  83 Apr 16 18:38 config
drwxrwxr-x. 1 aceuser aceuser  138 Apr 16 18:38 run
--ACE folder structure inside pod--
```

```
--log--
2020-04-16 18:42:17.799412: About to 'Start' the deployed resource 'message_flow_1' of type 'RestAPI'.
2020-04-16 18:42:17.800178: Deployed resource 'gen.message_flow_1' (uuid='gen.message_flow_1',type='MessageFlow') successfully stopped.
2020-04-16 18:42:17.800290: Message Flow 'gen.message_flow_1', 'gen.message_flow_1' encountered a failure and could not start.
2020-04-16 18:42:17.800338: An exception occurred while starting the servlet engine connector. Exception text is No keystore configured
--log--
```

**Comment by IBMRob** [comment]
Hi @abudavis - You do still need to configure the integration server to use the keystore, this needs to be done via the server.conf.yaml overrides.

**Comment by abudavis** [comment]
Thank you very much @IBMRob  :) That was it !
