### ISSUE TITLE
Docker build Error at Go Build (cannot find package error message)

### ISSUE THREAD

**Issue by mohammednaseem** [ot4i/ace-docker#117]
Step 1/42 : FROM golang:1.14.2 as builder
 ---> a1c86c07867e
Step 2/42 : ARG IMAGE_REVISION="Not specified"
 ---> Using cache
 ---> 223bc26dc0f6
Step 3/42 : ARG IMAGE_SOURCE="Not specified"
 ---> Using cache
 ---> aee36b60c3d6
Step 4/42 : COPY cmd/ ./cmd
 ---> Using cache
 ---> e45a2df20e71
Step 5/42 : COPY internal/ ./internal
 ---> Using cache
 ---> c3cb5bf095b2
Step 6/42 : COPY vendor/ ./vendor
 ---> Using cache
 ---> 64930f0ed7cd
Step 7/42 : RUN **go build** -ldflags "-X \"main.ImageCreated=$(date --iso-8601=seconds)\" -X \"main.ImageRevision=$IMAGE_REVISION\" -X \"main.ImageSource=$IMAGE_SOURCE\"" ./cmd/runaceserver/
 ---> Running in fac3890db5ff
cmd/runaceserver/integrationserver.go:31:2: **cannot find package "github.com/ot4i/ace-docker/internal/command"** in any of:
	/usr/local/go/src/github.com/ot4i/ace-docker/internal/command (from $GOROOT)
	/go/src/github.com/ot4i/ace-docker/internal/command (from $GOPATH)
cmd/runaceserver/logging.go:23:2: **cannot find package "github.com/ot4i/ace-docker/internal/logger"** in any of:
	/usr/local/go/src/github.com/ot4i/ace-docker/internal/logger (from $GOROOT)
	/go/src/github.com/ot4i/ace-docker/internal/logger (from $GOPATH)
cmd/runaceserver/main.go:25:2: **cannot find package "github.com/ot4i/ace-docker/internal/metrics" in any of:**
	/usr/local/go/src/github.com/ot4i/ace-docker/internal/metrics (from $GOROOT)
	/go/src/github.com/ot4i/ace-docker/internal/metrics (from $GOPATH)
cmd/runaceserver/integrationserver.go:32:2: **cannot find package "github.com/ot4i/ace-docker/internal/name" in any of:**
	/usr/local/go/src/github.com/ot4i/ace-docker/internal/name (from $GOROOT)
	/go/src/github.com/ot4i/ace-docker/internal/name (from $GOPATH)
cmd/runaceserver/integrationserver.go:33:2: **cannot find package "github.com/ot4i/ace-docker/internal/qmgr" in any of:**
	/usr/local/go/src/github.com/ot4i/ace-docker/internal/qmgr (from $GOROOT)
	/go/src/github.com/ot4i/ace-docker/internal/qmgr (from $GOPATH)
cmd/runaceserver/signals.go:23:2: **cannot find package "golang.org/x/sys/unix" in any of:**
	/usr/local/go/src/golang.org/x/sys/unix (from $GOROOT)
	/go/src/golang.org/x/sys/unix (from $GOPATH)
cmd/runaceserver/integrationserver.go:34:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/go/src/gopkg.in/yaml.v2 (from $GOPATH)

hopefully someone can help..

**Comment by IBMRob** [comment]
Please can you provide your docker build command along with the directory location your running it from.

**Comment by mohammednaseem** [comment]
Rob-

My bad,...
I was running from the wrong directory and to fix that I messed with the WORKDIR command.
(I am new to linux and Go)

Then I moved to the correct directory. But forgot about putting back the WORKDIR command.

Now it is working. Well actually I have gone further down and seeing some other errors. Hopefully I will fix it on my own. 

thank you for your time..
