### ISSUE TITLE
Docker build error of "ubi/Dockerfile.aceonly"  file.

### ISSUE THREAD

**Issue by skskcco2o17** [ot4i/ace-docker#120]
while running OpenShift oc command to build the ace server using ubi/Dockerfile.aceonly, i am getting below error 

```
--> WORKDIR /go/src/github.com/ot4i/ace-docker/
--> ARG IMAGE_REVISION="Not specified"
--> ARG IMAGE_SOURCE="Not specified"
--> COPY cmd/ ./cmd
error: build error: stat /tmp/build/inputs/ubi/cmd: no such file or directory
```

Please help

**Comment by IBMRob** [comment]
Can you provide the command you are using to build the image? 

All of our containers were designed around using docker to build them.

**Comment by skskcco2o17** [comment]
I use below command to build my  ace service  (ibm-appconnect-srvc) which I have create using `$oc new-app`  command from git dockerfile.

`$oc start-build bc/ibm-appconnect-srvc`
This command is giving me the error.

**Comment by IBMRob** [comment]
The error looks like its failing to find the file in question. Are you running the `oc`  command from the root of the repo? I think you will need to run the command with options such as 
```
$oc start-build --from-file=ubi/Dockerfile.aceonly bc/ibm-appconnect-srvc
```
