### ISSUE TITLE
Issues with Mqclient container 

### ISSUE THREAD

**Issue by abharku** [ot4i/ace-docker#122]
There is no default value for MQ_URL so it fails in install-mq.sh. Either need to explain how to obtain and pass a url or need to have some default value.

MQSeriesJRE*rpm need to be mentioned in MQ_PACKAGES as it fails complaining that it's a prerequisite GSkit

**Comment by IBMRob** [comment]
We are about to update our docs and will make sure we include this information in the docs. 

In the meantime the values required are:
ARG MQ_URL - URL to a tar file which includes the linux MQ Server installation files i.e. 9.1.5.0-IBM-MQ.tar.gz. This can be downloaded from Passport Advantage i.e. IBM MQ V9.1.5 Continuous Delivery Release for Ubuntu on x86 64-bit Multilingual (CC0AJML) 
ARG MQ_URL_USER - Username to access tar file
ARG MQ_URL_PASS - Password to access tar file

Can you provide some more information on the failure you are seeing. These files are exactly what we use to build all our server images and are not seeing this issue

**Comment by abharku** [comment]
I used 9.0.0.10

https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+MQ&release=9.0.0.10&platform=All&function=fixId&fixids=9.0.0.10-IBM-MQC-*,9.0.0.10-IBM-MQ-Install-Java-All,9.0.0.10-IBM-MQ-Java-InstallRA&useReleaseAsTarget=true&includeSupersedes=0&source=fc

**Comment by IBMRob** [comment]
There is a new sample on how to install MQ into an ACE image - https://github.com/ot4i/ace-docker/tree/main/samples/mqclient
