### ISSUE TITLE
Extending size of integration server event logs for ACE on CP4I

### ISSUE THREAD

**Issue by abudavis** [ot4i/ace-docker#123]
Hello, we are running ACE 11.0.0.8 on CP4I 2020.1.1 and have seen that on a busy integration that runs off the ace integration server pod, the event logs tend to wrap at a certain size (located at /home/aceuser/ace-server/log/ directory on the pod).

Could you please tell how to extend the size of integration server event logs?

Example:
```
sh-4.2$ ls -ltr
total 43152
-rw-r-----. 1 aceuser aceuser        0 Jun 24 10:32 integration_server.acepod.events.txt.5
-rw-r-----. 1 aceuser aceuser 10485546 Jun 24 11:25 integration_server.acepod.events.txt.4
-rw-rw----. 1 aceuser aceuser 10485594 Jun 24 13:03 integration_server.acepod.events.txt.3
-rw-rw----. 1 aceuser aceuser 10485571 Jun 24 13:43 integration_server.acepod.events.txt.2
-rw-rw----. 1 aceuser aceuser 10485651 Jun 24 15:41 integration_server.acepod.events.txt.1
-rw-rw----. 1 aceuser aceuser  2242460 Jun 24 17:46 integration_server.acepod.events.txt
```

**Comment by lux01** [comment]
Hi @abudavis,

The `Log` stanza of the `server.conf.yaml` contains three settings related to the event log:

* `eventLog`: Set the base filepath for the event log. The default is in the `log` directory of the work directory, with the file name `integration_server.[server_name].events.txt`.
* `eventLogFileSize`: The maximum size is MB an event log file can be before it is rotated into a new file.
* `eventLogFileCount`: The maximum number of event log files that can be used for log rotation. If this number is reached and a new file is needed, the oldest file is deleted.

The full `Log` stanza of the `server.conf.yaml` file is described below:

```
Log:
  #consoleLog: true          # Control writing BIP messages to standard out. Set to true or false, default is true.
  #outputFormat: 'text'      # Control the format of BIP messages written to standard out and file. Set to ibmjson or text, default is text.
  #eventLog: '[iib.system-work-dir]/log/[iib.system-node-label].[iib.system-server-label].events.txt'     # Control writing BIP messages to file. Set to '' to disable, default is as shown.
  #eventLogFileSize: 10      # The maximum size in MB of an event log file before it is rotated into a new file
  #eventLogFileCount: 10     # The maximum number of event log files that should be rotated between.
  #elkLog: false             # Control the publication of BIP messages to an ELK (Elasticsearch, Logstash, Kibana) stack. Set to true or false, default is false.
  #elkConnections: ''        # Name of the ELK connection to use, for example 'elkConnection1'
                             # Each named ELK Connection must be defined in the ELKConnections section below.
```

**Comment by abudavis** [comment]
Thank you @lux01 :)
