### ISSUE TITLE
Unable to configure default remote queue manager for ace server

### ISSUE THREAD

**Issue by AshwinPai1981** [ot4i/ace-docker#125]
Hi
I am working on configuring a default remote queue manager for an ace server. What i have done so far
1.  Created MQEndpoint policy (MQClientConnection.policyxml) and copied the .policyxml and policy.descriptor under initial-config/policy folder.

2. Added the Default policies & set the remoteDefaultQueueManager as below. Please note under default policies, i have tried MQConnector: 'MQClientConnection' -- this gives me an error while server starts up (An unexpected property 'Defaults/Policies/MQConnector' with value 'MQClientConnection' was encountered when loading a YAML configuration.)

MQEndpoint: 'MQClientConnection' -- This doesnt throw any error about unexpected property.

<pre>
---
remoteDefaultQueueManager: '{DefaultPolicies}:MQClientConnection'
replacementQueuePrefix: 'STAGE5'
ResourceManagers:
  JVM:
    truststoreType: 'JKS'
    truststoreFile: '/home/aceuser/ace-server/truststore.jks'
    truststorePass: 'setdbparms::truststore'
Defaults:
 defaultApplication: ''       # Name a default application under which independent resources will be placed
 policyProject: 'DefaultPolicies'   # Name of the Policy project that will be used for unqualified Policy references
 Policies:
   mqConnector: 'MQClientConnection'

</pre>

3. My docker file.
<pre>
FROM ibmcom/ace-mqclient:11.0.0.8-r1-amd64

USER root

ARG BAR1=TestApp.bar

COPY ${BAR1} /home/aceuser/bars/

RUN ace_compile_bars.sh

USER aceuser
</pre>

4. When i start the container mounting initial-config, i see the below 2 errors. If i use MQEndpoint as the property name in the Defaults/Policies then i only see the latter error about policy not being found.
<pre>
2020-07-15T08:17:33.411Z Waiting for integration server to be ready
2020-07-15T08:17:33.425Z Integration server not ready yet
.2020-07-15 08:17:33.878680: An unexpected property 'Defaults/Policies/mqConnector' with value 'MQClientConnection' was encountered when loading a YAML configuration. 
....2020-07-15 08:17:33.882552: .2020-07-15 08:17:33.882820: Integration server 'ACESERVER' starting initialization; version '11.0.0.8' (64-bit) 
....2020-07-15 08:17:33.905500: IBM App Connect Enterprise internal error: diagnostic information 'Fatal Error; exception thrown before initialisation completed', 'MQ Director', '199', '199', '11', '10'. 
2020-07-15 08:17:33.905688: BIP2203E: An integration server has encountered a problem whilst starting. 
2020-07-15 08:17:33.905760: BIP1388E: Policy'{DefaultPolicies}:MQClientConnection' of type 'MQ' is required for server startup, but is not present. 
main checker destroyed before initialisation completed, latest stage was MQ Director, pid 199, tid 199, attempted stage was 11 and 10 stages completed
2020-07-15 08:17:33.905932: BIP1992I: Integration server 'ACESERVER' stopped. 
</pre>

Can you please assist with a sample of how to configure a default remote queue manager for an ace sever?

Thanks and Regards
Ashwin

**Comment by IBMRob** [comment]
Hi Ashwin,

We are aware of a problem in App Connect Enterprise which means that the default QM doesn't work properly if its defined using overrides (like we do in the container). The work around at the moment is to put the policy into the bar file. 

We are looking to resolve this issue in the next release of ACE

**Comment by AshwinPai1981** [comment]
Thank you so much @IBMRob . Appreciate the quick response.

**Comment by Cuball0** [comment]
Hello @IBMRob 

Any status on this?  We are having the same issue...

Does this mean that the functionality of using a polcyxml in init-config folder never works?  So the only option is adding a Policy to the bar ?
I find adding a policy to the bar a bit difficult as we use the bar file for different environments.  And use the policy file to choose the environment (QMGR).

**Comment by mattbaileyuk** [comment]
@Cuball0 What version of ACE are you using? I believe that was fixed in 11.0.0.10; pulling `ibmcom/ace-server` should give you an image using 11.0.0.10 (or you can pull in a specific build [using the Dockerhub page as a guide](https://hub.docker.com/repository/docker/ibmcom/ace-server))

**Comment by Cuball0** [comment]
@mattbaileyuk 

We are using the 11.0.0.9 image... 
I'll see if I can upgrade to the .10

**Comment by rgopalan1** [comment]
@mattbaileyuk  and @IBMRob  We are using 11.0.0.10 still we are getting the same error. I am currently using TimeoutControl and TimeoutNotification Node in my msgflow and trying to connect to the remote queue manager.

**Comment by hondab** [comment]
Having the same issue with ACE 11 FP12 when just specifying the remoteDefaultQueueManager: '{Default}:MQQM1' however when I also specify defaultQueueManager: 'MQQM1'  it works when I run as a container, however outside of a container I get: A broken connection to IBM MQ queue manager has been reported with IBM MQ reason code '2568'

**Comment by bthomps** [comment]
@hondab .... Note that the server.conf.yaml specifically records that the remoteDefaultQueueManager and defaultQueueManager properties should not both be used ... you should see this comment in the file:

`# The remoteDefaultQueueManager and defaultQueueManager properties are mutually exclusive. Only uncomment one of these two options.`

It's not clear what you mean by "outside a container" ... Note that remoteDefaultQueueManager is only intended for independent integration servers and not supported for node-owned servers (https://www.ibm.com/docs/en/app-connect/11.0.0?topic=mq-using-remote-default-queue-manager).

**Comment by rgopalan1** [comment]
> @hondab .... Note that the server.conf.yaml specifically records that the remoteDefaultQueueManager and defaultQueueManager properties should not both be used ... you should see this comment in the file:
> 
> `# The remoteDefaultQueueManager and defaultQueueManager properties are mutually exclusive. Only uncomment one of these two options.`
> 
> It's not clear what you mean by "outside a container" ... Note that remoteDefaultQueueManager is only intended for independent integration servers and not supported for node-owned servers (https://www.ibm.com/docs/en/app-connect/11.0.0?topic=mq-using-remote-default-queue-manager).

Following is my server.conf.yaml
serverConfVersion: 1

#trace: none                 # choose 1 of : none|service|diagnostic
#traceSize: 1G               # Set the service trace size
#traceNodeLevel: true        # Enable or disable Trace Nodes

remoteDefaultQueueManager: '{TireMQPolicy}:RemoteMQEndpoint'


Defaults:
  #defaultApplication: ''             # Name a default application under which independent resources will be placed
                                      # Defaults to the <name of the integration server>_DefaultApplication for integration servers owned by integration nodes
  policyProject: 'DefaultPolicies'   # Name of the Policy project that will be used for unqualified Policy references, default is 'DefaultPolicies'
  Policies:
    # Set default policy names, optionally qualified with a policy project as {policy project}:name
    #HTTPConnector: ''           # Default HTTP connector policy
    #HTTPSConnector: ''          # Default HTTPS connector policy


Still I am getting the same error
BIP1388E: Policy'{TireMQPolicy}:RemoteMQEndpoint' of type 'MQ' is required for server startup, but is not present.

**Comment by rgopalan1** [comment]
> Hi
> I am working on configuring a default remote queue manager for an ace server. What i have done so far
> 
> 1. Created MQEndpoint policy (MQClientConnection.policyxml) and copied the .policyxml and policy.descriptor under initial-config/policy folder.
> 2. Added the Default policies & set the remoteDefaultQueueManager as below. Please note under default policies, i have tried MQConnector: 'MQClientConnection' -- this gives me an error while server starts up (An unexpected property 'Defaults/Policies/MQConnector' with value 'MQClientConnection' was encountered when loading a YAML configuration.)
> 
> MQEndpoint: 'MQClientConnection' -- This doesnt throw any error about unexpected property.
> 
> ---
> remoteDefaultQueueManager: '{DefaultPolicies}:MQClientConnection'
> replacementQueuePrefix: 'STAGE5'
> ResourceManagers:
>   JVM:
>     truststoreType: 'JKS'
>     truststoreFile: '/home/aceuser/ace-server/truststore.jks'
>     truststorePass: 'setdbparms::truststore'
> Defaults:
>  defaultApplication: ''       # Name a default application under which independent resources will be placed
>  policyProject: 'DefaultPolicies'   # Name of the Policy project that will be used for unqualified Policy references
>  Policies:
>    mqConnector: 'MQClientConnection'
> 
> 1. My docker file.
> 
> FROM ibmcom/ace-mqclient:11.0.0.8-r1-amd64
> 
> USER root
> 
> ARG BAR1=TestApp.bar
> 
> COPY ${BAR1} /home/aceuser/bars/
> 
> RUN ace_compile_bars.sh
> 
> USER aceuser
> 1. When i start the container mounting initial-config, i see the below 2 errors. If i use MQEndpoint as the property name in the Defaults/Policies then i only see the latter error about policy not being found.
> 
> 2020-07-15T08:17:33.411Z Waiting for integration server to be ready
> 2020-07-15T08:17:33.425Z Integration server not ready yet
> .2020-07-15 08:17:33.878680: An unexpected property 'Defaults/Policies/mqConnector' with value 'MQClientConnection' was encountered when loading a YAML configuration. 
> ....2020-07-15 08:17:33.882552: .2020-07-15 08:17:33.882820: Integration server 'ACESERVER' starting initialization; version '11.0.0.8' (64-bit) 
> ....2020-07-15 08:17:33.905500: IBM App Connect Enterprise internal error: diagnostic information 'Fatal Error; exception thrown before initialisation completed', 'MQ Director', '199', '199', '11', '10'. 
> 2020-07-15 08:17:33.905688: BIP2203E: An integration server has encountered a problem whilst starting. 
> 2020-07-15 08:17:33.905760: BIP1388E: Policy'{DefaultPolicies}:MQClientConnection' of type 'MQ' is required for server startup, but is not present. 
> main checker destroyed before initialisation completed, latest stage was MQ Director, pid 199, tid 199, attempted stage was 11 and 10 stages completed
> 2020-07-15 08:17:33.905932: BIP1992I: Integration server 'ACESERVER' stopped. 
> Can you please assist with a sample of how to configure a default remote queue manager for an ace sever?
> 
> Thanks and Regards
> Ashwin


> Hi Ashwin,
> 
> We are aware of a problem in App Connect Enterprise which means that the default QM doesn't work properly if its defined using overrides (like we do in the container). The work around at the moment is to put the policy into the bar file.
> 
> We are looking to resolve this issue in the next release of ACE

Hi Rob,
I am currently created a custom docker image using ACE-11.0.0.10 version. I am using TimeoutControl and TimeoutNotification Nodes in my application which requires QM and Queues for processing.  Please kindly help me to resolve this issue.
serverConfVersion: 1

#trace: none                 # choose 1 of : none|service|diagnostic
#traceSize: 1G               # Set the service trace size
#traceNodeLevel: true        # Enable or disable Trace Nodes

remoteDefaultQueueManager: '{TireMQPolicy}:RemoteMQEndpoint'


Defaults:
  #defaultApplication: ''             # Name a default application under which independent resources will be placed
                                      # Defaults to the <name of the integration server>_DefaultApplication for integration servers owned by integration nodes
  policyProject: 'DefaultPolicies'   # Name of the Policy project that will be used for unqualified Policy references, default is 'DefaultPolicies'
  Policies:
    # Set default policy names, optionally qualified with a policy project as {policy project}:name
    #HTTPConnector: ''           # Default HTTP connector policy
    #HTTPSConnector: ''          # Default HTTPS connector policy


Error:
BIP1388E: Policy'{TireMQPolicy}:RemoteMQEndpoint' of type 'MQ' is required for server startup, but is not present.

**Comment by bthomps** [comment]
Hi @rgopalan1

To configure a remote default queue manager, the important setting is the remoteDefaultQueueManager setting in your server.conf.yaml file, which in your example you have stated is currently set to '{DefaultPolicies}:MQClientConnection'. This is telling ACE to locate the MQ connection information by reading MQClientConnection.policyxml, which is expected to be found in a Policy Project named DefaultPolicies.

Incidentally, you have also configured DefaultPolicies to be the name of your default policy project. Typically a default policy project is only used in cases where you have migrated from an earlier version of IIB, and have been left with migrated configurable services which have been placed into a single "default policy project" to help you begin to adopt ACEv11 by making the bare minimum of configuration changes to the product. In general, most users of ACEv11 will not need to use a default policy project at all, and instead will just define their policies inside policy projects of their own chosen names.

There are then two errors reported by the server when it is started:

1. It is confused to have found the entry in your server.conf.yaml under Defaults/Policies/mqConnector ... In the Defaults/Policies section you can set defaults for an HTTPConnector policy type or a monitoringProfile (as indicated by the comments in the example server.conf.yaml file) but "mqConnector" is not expected syntax in this area of the yaml. If you were to remove this entry from your yaml I would expect the following error which you are receiving to no longer be reported: "An unexpected property 'Defaults/Policies/mqConnector' with value 'MQClientConnection' was encountered when loading a YAML configuration."

2. It cannot find the policy named RemoteMQEndpoint.policyxml inside policy project named TireMQPolicy. Rob reported earlier up this issue that there is a known issue whereby currently the policy used to locate the remote default queue manager cannot be provided through the overrides directory and must be supplied in the BAR file. When deployed, BAR files end up being unzipped into the "run" subdirectory of the working directory. Given that you are building your own custom image, to workaround this known issue, can I suggest that you place in the run directory a subdirectory named TireMQPolicy (to represent the policy project) and in this subdirectory place the policy descriptor and RemoteMQEndpoint.policyxml. This should then be found by the server when it starts and thus avoid the BIP1388E which you are experiencing. 

Cheers,
Ben

**Comment by hondab** [comment]
Thanks for the confirmation that defaultRemote Queue Managers can only be used inside of a Stand Alone Integration Server,

**Comment by tdolby-at-uk-ibm-com** [comment]
To clear up any confusion about policies in the overrides directory: that issue was indeed fixed in ACE 11.0.0.10 and so any containers built using that level or later should not have any problems due to the overrides issue identified at the top of this issue.

**Comment by tdolby-at-uk-ibm-com** [comment]
@rgopalan1 - not sure if you've solved this already, but I've put together some working examples for the remote default QM settings here [https://github.com/tdolby-at-uk-ibm-com/ace-remoteQM-policy ](https://github.com/tdolby-at-uk-ibm-com/ace-remoteQM-policy) showing various ways of adding credentials in, setting QM host/port, etc. Assuming you have a queue manager available to test it out, it should be possible to try out the examples pointing at your QM to see how it goes, and then see if there are any differences between your configuration and the (working) examples.

The examples use MQ on Cloud (see https://www.ibm.com/cloud/mq) by default, which is very easy to get going and has a free tier available, just in case that's easier to work with while testing the remote capability. 

Examples include both the ACE certified container (running without the App Connect Operator) and plain docker images built from the ACE software and MQ client tar files directly.

**Comment by rgopalan1** [comment]
@tdolby-at-uk-ibm-com Thank you so much for your help. I will try your solution and get back to you.

**Comment by IBMRob** [comment]
@sukesh-kr. The policyxml mechanism is a legacy mechanism designed for the help charts. When using this image with the App Connect operator we support “policy” configurations which allow them to be mounted into the container 

if you believe there is still an issue please raise a PMR
