### ISSUE TITLE
How to create Integration Node in ACE Docker Container ?

### ISSUE THREAD

**Issue by AbdullaElshourbagy** [ot4i/ace-docker#127]
How to create Integration Node in ACE Docker Container ?
and create multiple integration server in integration node.

**Comment by IBMRob** [comment]
This isn't currently something we support / provide. As part of the re-architecture of V11 we have updated the product to work better as single integration servers and have designed our container offering around that. 

Can I ask why you want to use an Integration Node?

**Comment by AbdullaElshourbagy** [comment]
In our company we need to move to Docker containers from IIB servers.
so we search to find best fit scenario to apply this migration from iib to ace and using ace through Docker.
