### ISSUE TITLE
Building ACE Developer with MQ Developer fails with current dockerfile configuration and latest MQ release

### ISSUE THREAD

**Issue by fbergeret95** [ot4i/ace-docker#128]
When building the image [following the instructions](https://github.com/ot4i/ace-docker#build-an-image-with-app-connect-enterprise-only) for a container with ace for developers + mq for developers, it fails. The root cause is that the [Dockerfile.acemq](https://github.com/ot4i/ace-docker/blob/master/ubi/Dockerfile.acemq) points to a non-existent mq container tag:
`ARG BASE_IMAGE=ibmcom/mq:9.1.5.0`

Furthermore if you update this line to the _latest_ tag, it will also fail while building, stating that the _mqm:mqm user doesn't exist._ I've also identified the root cause for this: in the [latest release (9.2.0)](https://github.com/ibm-messaging/mq-container/blob/9.2.0/Dockerfile-server) the user is **not** created, while for example in [9.1.4](https://github.com/ibm-messaging/mq-container/blob/9.1.4/Dockerfile-server) it is: [see this line](https://github.com/ibm-messaging/mq-container/blob/8a40b6a5dddf6636f6db5d40192d2bab9f55ac45/Dockerfile-server#L137).

Finally building the image using `ARG BASE_IMAGE=ibmcom/mq:9.1.4.0-r1` works as intended.

**Comment by IBMRob** [comment]
Thanks for spotting this. We will change the default value.
