### ISSUE TITLE
How can pull the ace docker image from your github ? 

### ISSUE THREAD

**Issue by zaheershaffi** [ot4i/ace-docker#132]
Hi Dear , 
I want to deploy the ACE on open shift , so i want to use laster docker image 11.0.0.9 that is updated in your gitHUB , can you please help me out in this? 
How can i pull the image from your github repository ?

**Comment by mattbaileyuk** [comment]
This GitHub repo doesn't have a direct build chain from it, but we do use the Dockerfiles on here to build the ACE server developer edition images which we then [upload to Dockerhub](https://hub.docker.com/r/ibmcom/ace-server) alongside each App Connect Operator release (so they are updated with a release and not with every change here).
