### ISSUE TITLE
ace-mqclient mqsisetdbparms

### ISSUE THREAD

**Issue by niconiew** [ot4i/ace-docker#133]
Apologies if posting this at the wrong place. Having a question about image '**ibmcom/ace-mqclient**'
Can someone please guide me to whom or where to post the below question for assistance?

In short, trying to run commands like "`mqsisetdbparms`" in the container's shell, but getting error "**Command not found**".
When running it from path _/opt/ibm/ace-11/server/bin/_, getting below error
./mqsisetdbparms **error while loading shared libraries: libImbCmdLib.so: cannot open shared object file: No such file or directory**

Any assistance will be appreciated
Thanks

**Comment by IBMRob** [comment]
Before running any commands within the container you need to source the `mqsiprofile` i.e.

`. /opt/ibm/ace-11/server/bin/mqsiprofile` 

After running that you will be able to run mqsi commands.

**Comment by niconiew** [comment]
Thanks very much
