### ISSUE TITLE
encrypt admin-user.txt content

### ISSUE THREAD

**Issue by jaana-ibm** [ot4i/ace-docker#134]
Hi guys,

Could you tell me is there any way to encrypt admin-user.txt content so that username and password are not plaintext?

Thank you very much for the help.

**Comment by IBMRob** [comment]
Currently it's not possible to encrypt the admin-users.txt file. When the file gets copied into kube it does get put into a secret so the contents is encrypted at all times within the cluster once its left your laptop and only accessible by those who have authority to access the secret. 

We are looking to add support of Vault credentials in the future although no committed date at the moment.
