### ISSUE TITLE
Error with odbc configuration

### ISSUE THREAD

**Issue by niconiew** [ot4i/ace-docker#137]
Hi

Referring to [https://github.com/ot4i/ace-docker/issues/133](https://github.com/ot4i/ace-docker/issues/133)

Ran below 2 commands to setup profile and DBParms
```
sh-4.4$ . /opt/ibm/ace-11/server/bin/mqsiprofile
sh-4.4$ mqsisetdbparms -w  /home/aceuser/ace-server -n DB_HOSTNAME -u user -p passwrd
```
When testing the DB connection with command: `$ mqsicvp -n ESBDB -u user -p passwrd`

**ERROR1:**
_BIP8295E: ODBC environment variables have not been set, or are invalid.
The integration node cannot verify user data sources because the ODBCINI, ODBCSYSINI, or IE02_PATH environment variables are not set, or because the ODBCINI environment variable is set incorrectly.
Ensure that the ODBCINI environment variable is set, and see earlier warning messages for further detail_

**ERROR2:**
With ENV variable set: ODBCINI=/home/aceuser/ace-server/odbc.ini
Got the below error when running: `$ mqsicvp -n ESBDB -u user -p passwrd`

_BIP8290I: Verification passed for the ODBC environment.
 BIP2393E: Database error: ODBC return code '-1' from data source ''ESBDB'' using ODBC driver manager ''/opt/ibm/ace-11/ie02/lib/libodbcinterface.so''.
BIP2322E: Database error: SQL State ''HY000''; Native Error Code '6100'; Error Text ''[unixODBC][IBM][ODBC Oracle Wire Protocol driver]Invalid attribute (Serv) in AlternateServers.''
_BIP8040E: Unable to connect to the database.
The database cannot be accessed with the specified user Id and password pair.

Check that the database is running.
 - Check that the database has an adequate number of database connections available for use.
 - On Windows, check that an ODBC connection has been created.
 - On systems that use $ODBCINI, check that the file pointed to by $ODBCINI has been correctly updated.
 - On z/OS check the BIPDSNAO member of the component's dataset, and check the DB2 64bit ODBC driver (DSNAO64C) is in the STEPLIB.
 - Use mqsisetdbparms to set the password to the correct value and try again._

**Questions:**

1.  Could not find in the image documentation mention anything about setting ENV variable 'ODBCINI'.  Should it be set?
2.  Looking at ERROR2, does it seem if we missing a step, or may it be that our odbc.ini config file be be configured wrongly

Thanks

**Comment by IBMRob** [comment]
The ODBCINI env var is set in the container depending on whether an odbcini file exists. This is only set on the running process, not the container shell so any manual terminals launched will need the env car manually setting
