### ISSUE TITLE
setdbparms.txt not being read at startup

### ISSUE THREAD

**Issue by petervonh1** [ot4i/ace-docker#139]
Hi. Can any one assist me with a query relating to the above thread?
I'm using ACE 11.0.0.9
I'm trying to use mqsisetdbparms -w /home/aceuser/ace-server -n odbc::ESBDB -u xxx -p xxx in a setdbparms.txt file.
When I start my container the log shows:
`2020-10-05T12:08:22.429Z Processing configuration in folder setdbparms 2020-10-05T12:08:22.448Z+00:00 Handling setdbparms configuration 2020-10-05T12:08:22.452Z+00:00 setdbparms configuration complete`
This look to me like it hasn't processed my setdbparms statement in the setdbparms.txt file. This also seems to be confirmed by the output:
`sh-4.4$ mqsireportdbparms -w /home/aceuser/ace-server -n ESBDB -u xxx-p xxx BIP8208W: No resources found with resource name 'ESBDB'.`
mqsicvp looks correct:
`sh-4.4$ mqsicvp -n ESBDB -u xxx-p xxx
BIP8290I: Verification passed for the ODBC environment.

BIP8270I: Connected to Datasource 'ESBDB' as user 'UAFRESB'. The datasource platform is 'Oracle', version '12.02.0000 Oracle 12.2.0.1.0'.
===========================`
Thanks in advance

**Comment by MartinRoss-IBM** [comment]
When running mqsireportdbparms you need to use `-n odbc::ESBDB`:

```bash
$ mqsisetdbparms -w /tmp/blah -n odbc::ESBDB -u foo -p bar
BIP8071I: Successful command completion. 

$ mqsireportdbparms -w /tmp/blah -n ESBDB
BIP8208W: No resources found with resource name 'ESBDB'. 

BIP8071I: Successful command completion. 

$ mqsireportdbparms -w /tmp/blah -n odbc::ESBDB
BIP8180I: The resource name 'odbc::ESBDB' has userID 'foo'. 

BIP8071I: Successful command completion.
```
