### ISSUE TITLE
no matches for kind "Route" in version "route.openshift.io/v1"

### ISSUE THREAD

**Issue by victorpalmeida** [ot4i/ace-docker#141]
When installing IBM ACE on Vanilla Kubernetes I am getting the following error:

```
# Example installing IBM ACE via Helm charts
$ helm install ibm/ibm-ace-server-dev --name-template ace-dev --set license=accept --set persistence.enabled=true
```

**Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Route" in version "route.openshift.io/v1"**

I believe there must be an option to tell the helm chart to not install Route resource on non-OpenShift environments. How can I  do that, please?

Thank you.

**Comment by IBMRob** [comment]
The IBM helm charts do not support running on Kubernetes. They are only supported on Redhat Openshift. 

We have now moved away from using the helm charts and have an Operator which delivers similar capability. This currently is also limited to only running on OCP although support for Kubernetes is on the roadmap.
