### ISSUE TITLE
STEP RUN go mod download fails with error no route to host

### ISSUE THREAD

**Issue by nitgeek** [ot4i/ace-docker#142]
While running the docker build from ace-docker using ("`docker build -t ace-dev-only --build-arg ACE_INSTALL={ACE-dev-file-in-deps-folder} --file ubi/Dockerfile.aceonly .`"), getting the error mentioned at the end.

```
Step 1/43 : FROM golang:1.14.2 as builder
 ---> 2421885b04da
Step 2/43 : WORKDIR /go/src/github.com/ot4i/ace-docker/
 ---> Using cache
 ---> 05bbcb2ea320
Step 3/43 : ARG IMAGE_REVISION="Not specified"
 ---> Using cache
 ---> 46eddaa47c0c
Step 4/43 : ARG IMAGE_SOURCE="Not specified"
 ---> Using cache
 ---> ee0d958f5a5c
Step 5/43 : COPY go.mod .
 ---> Using cache
 ---> d60c2577fb2f
Step 6/43 : COPY go.sum .
 ---> Using cache
 ---> bafe8bc0807e
Step 7/43 : RUN go mod download
 ---> Running in a939339ea6e8
go: github.com/gorilla/websocket@v1.4.2: Get "https://proxy.golang.org/github.com/gorilla/websocket/@v/v1.4.2.mod": dial tcp: lookup proxy.golang.org on 192.168.0.1:53: read udp 172.17.0.2:36832->192.168.0.1:53: read: no route to host
The command '/bin/sh -c go mod download' returned a non-zero code: 1
```

**Comment by mattbaileyuk** [comment]
That's just going off to download a package from GitHub, so either there's a networking issue at your end or there was a problem on the server side. Browsing from my phone (not currently near a machine to try the Dockerfile) it looks alright right now so hopefully this was a temporary blip.

**Comment by nitgeek** [comment]
I thought earlier it as temporary, but I am facing it for a few days now. Can't see an apparent network issue at my end, because it downloaded the golang:1.14.2 with no issues.
