### ISSUE TITLE
Error - chown: invalid user: mqm:mqm

### ISSUE THREAD

**Issue by OmBabosa** [ot4i/ace-docker#144]
Hi,

We are building a **production image for _ACE with MQ_**. We updated the BASE_IMAGE to point to the Production MQ image from IBM container registry, and also downloaded the production version of ACE (IBM_ACE_11.0.10_LNX_X8664_INCTKT.tar.gz) from passport advantage. 

The image build fails at **step '41'** with the below error:

Step 40/49 : RUN chmod u+x /usr/local/bin/install-kubectl.sh   && install-kubectl.sh
 ---> Running in 9409cbe1ff3e
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Removing intermediate container 9409cbe1ff3e
 ---> 8b97984208c8
Step 41/49 : RUN mkdir /home/aceuser   && chown mqm:mqm /home/aceuser   && usermod -a -G mqbrkrs mqm   && usermod -d /home/aceuser mqm   && su - mqm -c '. /opt/ibm/ace-11/server/bin/mqsiprofile && mqsicreateworkdir /home/aceuser/ace-server'   && chmod 755 /usr/local/bin/*
 ---> Running in b858174bdcaf
**_chown: invalid user: âmqm:mqmâ**
The command '/bin/sh -c mkdir /home/aceuser   && chown mqm:mqm /home/aceuser   && usermod -a -G mqbrkrs mqm   && usermod -d /home/aceuser mqm   && su - mqm -c '. /opt/ibm/ace-11/server/bin/mqsiprofile && mqsicreateworkdir /home/aceuser/ace-server'   && chmod 755 /usr/local/bin/*' returned a non-zero code: 1_

We tried with the Github project from 'master' as well the 'latest' release. Get the same error in both cases. 

We are using the latest docker version (Docker version 19.03.13, build 4484c46d9d)

Thanks.

**Comment by IBMRob** [comment]
The ACE MQ dockerfiles currently only supports the MQ server images which have an mqm user id. I think the last compatible version was 9.1.4.0-r1. 

To use the latest images that supports running as anyiud the dockerfile would need modifying

**Comment by OmBabosa** [comment]
Thanks much Rob.

We could build the ACE-MQ image after we used cp.icr.io/cp/ibm-mqadvanced-server:9.1.4.0-r1-amd64. Thank you so much for your help!

**One question though** - do you plan to release a version of the Docker file that can be used with latest MQ images, say 'cp.icr.io/cp/ibm-mqadvanced-server-integration:**9.1.5.0**-r2-amd64' for which i had originally got the error? Thanks.

**Comment by IBMRob** [comment]
At the moment we have no plans to update the ACE+MQ docker files. We are moving away from using ACE+MQ in the same container because most of the functionality is now available using MQ Client connections. 

If you would like try and get it working we would accept a PR
