### ISSUE TITLE
ACE/CP4I - Mysql database connection 

### ISSUE THREAD

**Issue by sandisan** [ot4i/ace-docker#145]
I am new to CP4I. I am trying to connect to MySql DB from CP4I ACE instance. As I understand, we need to update odbc.ini & setdbparams file. How would be the odbc driver will installed? If there is any inputs or tutorial that can be shred it would help

**Comment by IBMRob** [comment]
MySQL is typically supported using JDBC. This can be done by either extending the image to include the MySQL client jar in the install class path or you can put it into the bar.
