### ISSUE TITLE
Keystore path not resolving

### ISSUE THREAD

**Issue by niconiew** [ot4i/ace-docker#147]
Hi 
Can someone please guide on how to solve the below issue, seems the keystore path cannot be located
Image used: https://hub.docker.com/r/ibmcom/ace-mqclient

**ACE Log Error:**
_An error occurred whilst performing an SSL socket operation. Operation: connect. Error Text: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target_

**Soap Response Error:**
_BIP3152S: Socket error detected whilst invoking Web service located at host 'host.com', port 443, path '/webservice'. : /jenkins/slot0/product-build/WMB/src/WebServices/WSBase/ImbWSRequest.cpp: 678: Imb::WSRequest::makeWSRequest: : 
BIP3165S: An error occurred whilst performing an SSL socket operation. Operation: 'connect'. Error Text: 'javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target'. : /jenkins/slot0/product-build/WMB/src/WebServices/WSBase/Socket.cpp: 1266: Imb::SocketJNIManager::handleGeneralJavaException:_ 

**Keystore Setup:**
Keystore Path: /home/aceuser/initial-config/keystore/client-keystore.jks  (contains the pvt key and certs)
ENV variable for password is set: ACE_KEYSTORE_PASSWORD

**Comment by jcreforme** [comment]
what was the solution? thank you
