### ISSUE TITLE
Embedded Global Cache in Replica Set on K8S/Openshift

### ISSUE THREAD

**Issue by nitgeek** [ot4i/ace-docker#149]
We are using Global Cache in IIB. When we move to ACE, Global cache works flawlessly in VM with multiple Integration Servers.
However, if I deploy my application on K8S, then I am unable to scale my application as the requests would get load balanced across the PODs and the key value pair updates will happen only in one pod while the rest of the PODs in the replica set won't receive the updates.

Is there a solution to this problem or are we saying that if an IntegrationServer uses Global Cache then we can't scale it?

Also, if I try to host the embedded cache as a seperate dedicated POD exposed with a K8S service and then configure the Integration server with my application as a client to access the  K8S service, then also it fails. The integration server hosting the embedded global cache rejects the connection, I get a Connection Refused error on the client Integration Server.
Please confirm if it is possible to connect the remote catalog server hosted via a seperate POD and K8S service.

**Comment by IBMRob** [comment]
Hi, unfortunately the Global Cache components is not supported in containers when used across multiple pods, this is a restriction in the underlying technology "IBM Xtreme Scale" unfortunately. It still works if you just need local in container caching but it doesn't work to cache across multiple integration servers. 

The one way its possible to get it to work with containers is by hosting the main global cache catalogs on standard VMs outside of the K8S environment and only use clients in the K8S environment

**Comment by nitgeek** [comment]
@IBMRob  Thanks for the reply Rob.
We were able to make it work with multiple pods with combination of stateful sets, headless service and service mesh's (istio) traffic mirroring feature.

**Comment by NitishGo** [comment]
@nitgeek could you please share what you have done to share the cache across the multiple replicas of the pods?
I'm having similar problem, my service reads/writes into a cache and its round-robin , so sometimes there is no response

**Comment by IBMRob** [comment]
Below is the current support statement 

The Global Cache feature in App Connect Enterprise is implemented using WebSphere Extreme Scale technology. WebSphere Extreme Scale is designed to offer a resilient cache topology by hosting a known number of catalog and container servers in a fixed topology. This is not compatible with the ephermeral nature of containers running in elastically scaled cloud environments such as Kubernetes. WebSphere Extreme Scale therefore does not support running the catalog or container server components in containerized environments including Kubernetes, docker or podman. Therefore App Connect Enterprise does not support running the embedded cache when running an ACE Integration Server in a containerized environment. It is still supported to make a client connection to an external WXS or DC10 grid when running in a container.

**Comment by psujeethkumar** [comment]
> Hi, unfortunately the Global Cache components is not supported in containers when used across multiple pods, this is a restriction in the underlying technology "IBM Xtreme Scale" unfortunately. It still works if you just need local in container caching but it doesn't work to cache across multiple integration servers.
> 
> The one way its possible to get it to work with containers is by hosting the main global cache catalogs on standard VMs outside of the K8S environment and only use clients in the K8S environment

Hello @IBMRob The local cache in containerised environment works except the cache expiry functionality. 
E.g. in Java, we are setting MbGlobalMap.getGlobalMap("myMap", new MbGlobalMapSessionPolicy(20)) expecting that the myMap should be removed from map after 20 seconds but that's not the case. 

We are using ACEv12.0.12.0 in Openshift platform.
