### ISSUE TITLE
mkdir in dockerfiles fail on re-runs

### ISSUE THREAD

**Issue by owhcom** [ot4i/ace-docker#152]
I hit countless issues with the builds not having MQ, when i hit upon the MQ add-on instructions, I used the "Dockerfile.acemq" file which then failed after the first mkdir as the directories already exist.
i've modified my copies to be "RUN mkdir -p" not too sure if you want to update this one too?

**Comment by IBMRob** [comment]
The ACE with MQ Server is no longer supported by this repo
