### ISSUE TITLE
ACE-MQ combined image fails to start

### ISSUE THREAD

**Issue by vishalbordia** [ot4i/ace-docker#158]
Hi,

We are building a production image for ACE with MQ. We updated the BASE_IMAGE to point to the Production MQ image from IBM container registry, and also downloaded the production version of ACE (IBM_ACE_11.0.10_LNX_X8664_INCTKT.tar.gz) from passport advantage and applied the fix pack TFIT34846.
MQ version which we are using is MQ9.2.0.0.

The image build is successful with no error, but while starting the image we get the error as attached below - 
[logs-ace-mq-image.log](https://github.com/ot4i/ace-docker/files/6815174/logs-ace-mq-image.log)

On the image build, we haven't customised anything at our end to build the combined ACE+MQ image. We are using the standard process detailed out on the GitHub at  'https://github.com/ot4i/ace-docker' and using the source code at revision 'IBM App Connect Operator - 11.0.0.9-r1' (https://github.com/ot4i/ace-docker/releases/tag/11.0.0.9-r1). At present, the combined image is based on ACE software binary taken from Passport advantage 'v11.0.0.11' and MQ certified image 'cp.icr.io/cp/ibm-mqadvanced-server:9.2.0.0-r3'.

**Comment by IBMRob** [comment]
The existing MQ source files only support the 9.1.4.0-r1 or earlier MQ images. The earlier MQ versions runs as a specific user vs the new versions of MQ which run as "AnyID". To get the newer MQ images working will need the docker file etc updating to handle running the whole container as AnyUI rather than the specific MQ image.

**Comment by vishalbordia** [comment]
Thanks IBMRob.
The error is complaining about 'Queue Manager does not exists', but I can see the queue manager is created already just before that error.
Also in the second part if you see in the bottom it complains about GOlang, so wondering if this build has different options set (queue and channel level stats ?) .that might be worth changing to see if it builds without them ? or if nothing has changed in this area ?
Any pointer on that front, what needs to be checked?

**Comment by IBMRob** [comment]
Unfortunately as noted above we have not attempted more recent MQ server builds so not aware of why changes would be required. The MQ Server option has now been removed from this repo
