### ISSUE TITLE
Needs Dockerfile samples for zSeries

### ISSUE THREAD

**Issue by jufis** [ot4i/ace-docker#160]
Hello,

We need samples on how to build a bar on zLinux/zSeries using Dockerfile. What is the recommended way to build an ACE bar inside Z using a dockerimage?

Also we need a location of the tarball as a replacement for http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/ for Z architecture s390

Any pointers/urls are all welcome!

Thank you for your support in advance!

Kind Regards,
Georgios

**Comment by IBMRob** [comment]
The images in this repo are used to build amd64, pLinux and zLinux images provided the right Installation binaries are installed.
