### ISSUE TITLE
How to add the datasource.json file to define a connection to a postgres database

### ISSUE THREAD

**Issue by mariaelisacf** [ot4i/ace-docker#162]
I want to use the LoopbackRequest node to connect to a Postgres database, however, I don't know where to add the datasource.json file and the models.

**Comment by tdolby-at-uk-ibm-com** [comment]
I think the v12 docs at https://www.ibm.com/docs/en/app-connect/12.0?topic=connectors-configuring-data-source-models-your-loopback-connector should provide the right info, though they're written with integration nodes in mind and therefore talk about "workpath" quite a bit. The container workpath is `/home/aceuser/ace-server/config` and the search order from the docs should be correct.

**Comment by IBMRob** [comment]
This repo has been updated to provide a new ACE image. If you think this issue is still applicable please re-open. 

For general ACE enquiries please use  https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?communitykey=77544459-9fda-40da-ae0b-fc8c76f0ce18
