### ISSUE TITLE
ACE not sending resource statistic events to remote IBM MQ

### ISSUE THREAD

**Issue by ofek** [ot4i/ace-docker#177]
Hello! Within this directory https://github.com/DataDog/integrations-core/tree/ibm-ace-docker/ibm_ace/tests/docker I'm doing

```
docker-compose -f docker-compose.yaml up -d
```

then based on

```
docker logs ibm-ace
```

everything looks fine. If, for example, I change the MQ policy's password there are indeed errors shown.

However, I don't see any of the topics listed here: https://www.ibm.com/docs/en/app-connect/12.0?topic=events-subscribing-event-message-topics

To confirm, I've been running

```
docker exec -it ibm-ace-mq runmqsc QM1
```

followed by

```
DISPLAY TPSTATUS('#')
```

cc @tdolby-at-uk-ibm-com @IBMRob Would either of you happen to know what's happening? Also, I noticed in https://github.com/ot4i/ace-docker/blob/master/internal/metrics/update.go that you're somehow scraping metrics without MQTT nor MQ. How is that possible? I'm very curious, as monitoring without setting up pub/sub would be quite ideal 🙂 

Thank you!!!

**Comment by ofek** [comment]
Hello again! Did you get a chance to look at this?

**Comment by ofek** [comment]
I'm still experiencing this issue.

**Comment by ofek** [comment]
Do either of you have an idea of what might be happening?

**Comment by IBMRob** [comment]
Hi, 

Regarding the metrics not sending on your ACE server I would recommend raising a PR so they can investigate the problem. 

The mechanism being used inside the container for pushing metrics to prometheus is that its taking the stats from an websocket. This is using an internal API which we would not recommend customers coding to as its liable to change. As we produce the container as part of the development team we can make the changes if/when the API changes.

**Comment by ofek** [comment]
Understood, thanks!
