### ISSUE TITLE
Lil path folders

### ISSUE THREAD

**Issue by kmmuragu** [ot4i/ace-docker#180]
Hi Team,

i would start by thanking the team for the awesome development of the ace container. The only request i would love for the team is provide a way for the user defined libraries to be mounted on the app connect  for there are many vendors who provide par and lil files that are needed to run specific functions and thus we are doing an upgrade and all our flows will not run for we are unable to configure the user library and also the generic files folder has provided a size limitation

**Comment by IBMRob** [comment]
This repo has been updated to provide a new ACE image. If you think this issue is still applicable please re-open. 

For general ACE enquiries please use  https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?communitykey=77544459-9fda-40da-ae0b-fc8c76f0ce18
