### ISSUE TITLE
multiline *-users.txt (admin,audit,operator,viewer) don't work

### ISSUE THREAD

**Issue by manoger** [ot4i/ace-docker#194]
#### Issue description
multiline *-users.txt (admin,audit,operator,viewer) don't work

#### Steps to reproduce the issue

1. Create a multiline admin-users.txt 
2. Create a new container
3. Try to login with the nth, after the first, user and password 

#### What's the expected result?

- Successfuly logging into the admin console

#### What's the actual result?

- Just the first user and password in the file works

#### Additional details / screenshot

- ![image](https://github.com/ot4i/ace-docker/assets/29717626/5e9b9a52-64dc-4422-8be6-9594cd8ed776)
- 
![image](https://github.com/ot4i/ace-docker/assets/29717626/50592950-549f-4c1d-9831-d537dc2a86ea)

**Comment by IBMRob** [comment]
Unfortunately the capability you describe was only ever described to support a user per role. 

This has also now been removed from the repo. If you would like to raise a PR which introduces a sample that provides this capability we can review it.
