### ISSUE TITLE
version number as variable

### ISSUE THREAD

**Issue by jwende** [ot4i/ace-docker#2]
Hi,
just as a proposal: 
you could manage a single dockerfile by providing the verion number as variable  if you stay with the numbering scheme from IIB ($version-IIB-LINUX64-DEVELOPER.tar.gz) and adopt this for ACE ($version-ACE-LINUX64-DEVELOPER.tar.gz) 
Similar approach for:
- overwriting the curl base address
- changing the name (going from DEV to PROD)
Cheers
J.

**Comment by dcb-robinson** [comment]
Hi, thanks for the proposal.

Your suggestion works well if you only want to change the binary installed, and that would work perfectly for the iib v10 images on ot4i/iib-docker. 

However, the move to ACE v11 is more than just a binary change. The running of an ACE v11 Integration Server is very different (and greatly simplified) from running Integration Servers in v10, hence the new repo and restructured image/files.
