### ISSUE TITLE
is there an image variant used for CI?

### ISSUE THREAD

**Issue by tuananh** [ot4i/ace-docker#202]
#### Issue description

we just want to create BAR file in CI. full image is too big for that.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by tuananh** [comment]
our situation is eks cluster using spot instances. k8s nodes come and go pretty often, resulting in very slow image pull when the node got re-created.

this is usually not a problem with on-premise cluster.

**Comment by IBMRob** [comment]
Check out https://github.ibm.com/Cloud-Integration/ot4i-ace-docker/tree/main/experimental for some options (Note these are currently unsupported but may help in this scenario

**Comment by tuananh** [comment]
> Check out https://github.com/ot4i/ace-docker/tree/main/experimental for some options (Note these are currently unsupported but may help in this scenario

none of these options is working in my case right? only the full version.
