### ISSUE TITLE
RHEL ACE Image Build : This system is not registered with an entitlement server. You can use subscription-manager to register.

### ISSUE THREAD

**Issue by VSA13** [ot4i/ace-docker#21]
Hi,

I am trying to build RHEL Ace Image on a VM. And i want to use the VM's licenses to build the image. But the build is pulling rhel image from FROM registry.access.redhat.com/rhel7 and failing due to **Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
There are no enabled repos.**
But when i run the updates on VM, the yum commands are successfully completed. Please let me know what changes to do in Dockerfile so as to use VM's subscription manager or how I can use VM's licenses when building image.

![image](https://user-images.githubusercontent.com/43268079/52283208-f756cd80-2959-11e9-85c6-c90800650317.png)

**Comment by IBMRob** [comment]
Hi,

As you have mentioned this is an issue with the entitlements. Your best to referring to the RedHat documentation which details what entitlements are required for building rhel Docker images

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/get_started_with_docker_formatted_container_images#creating_docker_images
and
https://access.redhat.com/solutions/1443553

**Comment by VSA13** [comment]
Hi Rob,

We have enabled the repositories on the host , but still the container is not able to access them. Can you please let me know if we have any other workaround or code fix which needs to be done to Dockerfile.

**Comment by IBMRob** [comment]
Hi,

I would recommend raising a support ticket with Redhat to find out why you can't build docker images. We have similar issues building the images as well and only have the correct licenses on specific machines that are able to build these images. A standard RHEL machine will typically not be able to build docker images.
