### ISSUE TITLE
The command '/bin/sh -c /opt/ibm/ace-11/ace make registry global accept license silently' returned a non-zero code: 127

### ISSUE THREAD

**Issue by VSA13** [ot4i/ace-docker#22]
Hi,

The Rhel build for ace fails due to below issue.

Step 5/18 : RUN /opt/ibm/ace-11/ace make registry global accept license silently
 ---> Running in 4314826e5b87

/bin/sh: /opt/ibm/ace-11/ace: No such file or directory
The command '/bin/sh -c /opt/ibm/ace-11/ace make registry global accept license silently' returned a non-zero code: 127

I am using 11.0.0.3-ACE-LINUX64-DEVELOP.tar.gz. (./build-rhel.sh ace-dev-only ace11 11.0.0.3-ACE-LINUX64-DEVELOP.tar.gz) to build the image.

Below are the file when I run tar xzf 11.0.0.3-ACE-LINUX64-DEVELOP.tar.gz

drwxrwxr-x.  2 root root  4096 Dec 19 12:55 extensions
drwxr-xr-x.  5 root root  4096 Dec 19 12:56 ie02
drwxrwxr-x.  2 root root  4096 Dec 19 12:56 swidtag
drwxrwxr-x. 15 root root  4096 Dec 19 12:56 readmes
drwxrwxr-x.  2 root root  4096 Dec 19 12:56 license
drwxrwxr-x.  1 root root 26616 Dec 19 12:56 ace
drwxrwxr-x. 13 root root  4096 Dec 19 12:56 tools
drwxrwxr-x. 36 root root  4096 Dec 19 12:56 server
drwxrwxr-x. 10 root root  4096 Dec 19 12:58 common

Please let me know why the build is failing even when ace file is present in the tar.

**Comment by IBMRob** [comment]
Hi,

It looks like there is a problem copying the files into the docker file. Can you show us what you have inside the directory "./rhel/ace-11"

**Comment by VSA13** [comment]
Hi,

Below are the files in copied in the container ace/builder. ace file is present in the container.
But the docker file is not able to execute the file.

![image](https://user-images.githubusercontent.com/43268079/52849231-755c6680-3108-11e9-8981-9e6074e01789.png)

**Comment by atulsingh0** [comment]
@IBMRob I am also having the same issue but when I looked into the "./rhel/ace-11" did not find the 
"ace" file

```
./rhel/ace-11> ll
total 3723724
-rw------- 1 root root 1677687473 Dec 31  1969 035631679ed16c52df5b8751d5e96961aafe82c5f32c17d4741b4c061fef30a8.tar.gz
-rw------- 1 root root 1348173242 Dec 31  1969 34cbe1f7769b028c91bb9735d3704210b8201d86113d477de695eadca003be65.tar.gz
-rw------- 1 root root  344909764 Dec 31  1969 752844ff4003067dea81ce471d7eca53b4c73c9a71a4dec983734d2ab8705545.tar.gz
drwxr-xr-x 2 root root       4096 May 22 11:14 ace-11
-rw------- 1 root root  247235787 Dec 31  1969 b1f59c25e58cbafd98c804e251eccbcb02ceb78db693bf39b37cdba656994d4e.tar.gz
-rw------- 1 root root  194801732 Dec 31  1969 f4e227e68dcc5f651f1b291d5dcede6b1b279c65a880525cdf17b9ec9c01fcbc.tar.gz
-rw------- 1 root root      85890 Dec 31  1969 ibm-ace-dashboard-rhel-prod-1.1.0.tgz
-rw------- 1 root root     171081 Dec 31  1969 ibm-ace-server-rhel-prod-1.1.0.tgz
```

**Comment by IBMRob** [comment]
@atulsingh0 - That looks like you have supplied the wrong install files. These docker files are designed to take the ACE install package. The file you have supplied looks like the App Connect Enterprise for ICP archive. This includes docker files and helm charts, not the install binaries

**Comment by atulsingh0** [comment]
Thanks @IBMRob , my mistake. It got resolved.
