### ISSUE TITLE
Could not create Docker image

### ISSUE THREAD

**Issue by patrick-marie** [ot4i/ace-docker#23]
$ sudo docker build -t ace-mq:11.0.0.3 --build-arg ACE_INSTALL=ace-docker-master/deps --file ace-docker-master/ubuntu/Dockerfile.acemq .
[sudo] password for ibmtec:
Sending build context to Docker daemon  27.61MB
Step 1/38 : ARG BASE_IMAGE=ibmcom/mq:9.1.0.0
Step 2/38 : FROM golang:1.10.3 as builder
 ---> d0e7a411e3da
Step 3/38 : WORKDIR /go/src/github.com/ot4i/ace-docker/
 ---> Using cache
 ---> 56defa02e68d
Step 4/38 : ARG IMAGE_REVISION="Not specified"
 ---> Using cache
 ---> c66cb082091c
Step 5/38 : ARG IMAGE_SOURCE="Not specified"
 ---> Using cache
 ---> b2e886e32d2d
Step 6/38 : COPY cmd/ ./cmd
COPY failed: stat /var/lib/docker/tmp/docker-builder477502786/cmd: no such file or directory

**Comment by IBMRob** [comment]
@patrick-marie - I suspect this is because your running the docker build command from the wrong directory. It needs to be run from the top level directory of the repo (i.e. cmd etc are in your current directory). Looking at your --file parameter I suspect your running the command from a level higher.

**Comment by patrick-marie** [comment]
Thanks you are right. By running the command from the right directory level, I can go further, although an other error remains:
$ cd ace-docker-master
$ sudo docker build -t ace-mq:11.0.0.3 --file ubuntu/Dockerfile.acemq .
Sending build context to Docker daemon  27.59MB
Step 1/38 : ARG BASE_IMAGE=ibmcom/mq:9.1.0.0
Step 2/38 : FROM golang:1.10.3 as builder
---> d0e7a411e3da
Step 3/38 : WORKDIR /go/src/github.com/ot4i/ace-docker/
---> Using cache
---> 56defa02e68d
Step 4/38 : ARG IMAGE_REVISION="Not specified"
---> Using cache
---> c66cb082091c
Step 5/38 : ARG IMAGE_SOURCE="Not specified"
---> Using cache
---> b2e886e32d2d
Step 6/38 : COPY cmd/ ./cmd
---> Using cache
---> f23e8046cf33
Step 7/38 : COPY internal/ ./internal
---> Using cache
---> 6ff24ec8f3e6
Step 8/38 : COPY vendor/ ./vendor
---> Using cache
---> cea92e652465
Step 9/38 : RUN go build -ldflags "-X \"main.ImageCreated=$(date --iso-8601=seconds)\" -X \"main.ImageRevision=$IMAGE_REVISION\" -X \"main.ImageSource=$IMAGE_SOURCE\"" ./cmd/runaceserver/
---> Using cache
---> 0134d63330a5
Step 10/38 : RUN go build ./cmd/chkaceready/
---> Using cache
---> c2d36329424e
Step 11/38 : RUN go build ./cmd/chkacehealthy/
---> Using cache
---> 99e2360eeca7
Step 12/38 : RUN go test -v ./cmd/runaceserver/
---> Using cache
---> efe4a8491ab8
Step 13/38 : RUN go test -v ./internal/...
---> Using cache
---> 1ef04d0afab6
Step 14/38 : RUN go vet ./cmd/... ./internal/...
---> Using cache
---> 918d784f60b8
Step 15/38 : FROM ubuntu:16.04 as aceinstall
---> 7e87e2b3bf7a
Step 16/38 : ARG ACE_INSTALL=ace-11.0.0.2.tar.gz
---> Using cache
---> 48dbd77e757a
Step 17/38 : WORKDIR /opt/ibm
---> Using cache
---> 0e04c3b8dd99
Step 18/38 : COPY deps/$ACE_INSTALL .
COPY failed: stat /var/lib/docker/tmp/docker-builder158871014/deps/ace-11.0.0.2.tar.gz: no such file or directory

**Comment by patrick-marie** [comment]
The problem is fixed now.
