### ISSUE TITLE
Please add support for shared-classes

### ISSUE THREAD

**Issue by panho66** [ot4i/ace-docker#27]
Please add support for shared-classes
copy dependency jar files to /var/mqsi/shared-classes or /home/aceuser/ace-server/shared-classes

**Comment by IBMRob** [comment]
Hi - We will look to add this to our list of enhancements.

Can I check which use case you're looking to enable with this capability?

**Comment by panho66** [comment]
hi
one of the use case

https://www.ibm.com/support/knowledgecenter/en/SSTTDS_11.0.0/com.ibm.etools.mft.doc/ac28600_.htm

The JMS provider might supply additional JAR files that are required for transactional support; for more information, see the documentation that is supplied with the JMS provider. For example, on distributed systems, the WebSphere MQ JMS provider supplies an extra JAR file, com.ibm.mqetclient.jar.
You must add any additional JAR files to the shared_classes directory:

- Linux platformOn Linux: var/mqsi/shared-classes.
- Windows platformOn Windows: C:\ProgramData\IBM\MQSI\shared-classes.

**Comment by panho66** [comment]
hi 
use case 2

https://www.ibm.com/support/knowledgecenter/en/SSTTDS_11.0.0/com.ibm.etools.mft.doc/bk58210_.htm

**Independent integration servers:**
The Java shared classloader loads all the JAR files that are located within the shared-classes directories. JAR files are placed in the shared-classes directory under the integration server work directory for the integration server. For example, if the work directory passed to the IntegrationServer command on startup is /Users/user1/workDir1, the shared-classes directory is /Users/user1/workDir1/shared-classes

Integration server start with workpath 
command.RunAsUserBackground("aceuser", "ace_integration_server.sh", log, "-w", "/home/aceuser/ace-server", "--name", serverName, ...............

so shared-classes path is  /home/aceuser/ace-/shared-classes

**Comment by IBMRob** [comment]
Thanks

**Comment by preethiram4** [comment]
Hi, 

Is there a way to add external jars to shared class during integration server creation ? If you have any documents with the steps, can u share here ?

Thanks

**Comment by psujeethkumar** [comment]
Hi,

Is this enhancement is in progress ?This is big blocker to migrate implementation with custom nodes into containerised environments. 

Or may be this is fixed but not documented anywhere .

**Comment by trevor-dolby-at-ibm-com** [comment]
@psujeethkumar @preethiram4 ACE v12 does have support for adding JARs to shared-classes in the container image and also has a way of extending the shared-classes search path; see https://community.ibm.com/community/user/integration/blogs/trevor-dolby/2022/11/01/ace-shared-classes-and-containers for more information.

The key server.conf.yaml parameters are already in the sample server.conf.yaml in a local work directory:
```
#additionalJpluginDirectories: ''       # Extra directories to search for Java plugins; can reference shared libraries using '{shlibname}' syntax.
#additionalSharedClassesDirectories: '' # Extra directories to add to the shared classloader search path; can reference shared libraries using '{shlibname}' syntax.
```
and the blog post describes this in more detail. 

https://github.com/trevor-dolby-at-ibm-com/ace-shared-classes contains examples for the blog post, too, and those may help in getting going.

**Comment by psujeethkumar** [comment]
@trevor-dolby-at-ibm-com  Thanks for the reply & detailed blog.  Do this procedure can also be applied to deploy user-defined java classes ?

**Comment by trevor-dolby-at-ibm-com** [comment]
I believe so, yes, though I don't have any examples to point to for it. If you're building your own images then it's reasonably straightforward to add Java plugins during the build and then adjust the configuration as needed to pick them up.

If you're using only the IBM-supplied certified images in CP4i, then the `additionalJpluginDirectories` setting can be used to point to a deployed shared library that contains the Java plugins. It would be very similar to the shared classes approach described in the blog post, but using a different setting in server.conf.yaml,

**Comment by IBMRob** [comment]
This repo has been updated to provide a new ACE image. If you think this issue is still applicable please re-open. 

For general ACE enquiries please use  https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?communitykey=77544459-9fda-40da-ae0b-fc8c76f0ce18

**Comment by psujeethkumar** [comment]
@IBMRob @trevor-dolby-at-ibm-com  Sorry for delay, caught up on other priorities. 

We have several user defined nodes implemented in Java. So, my previous question is what is equivalent setting to make the hat containing the custom nodes to the integration server when deployed in Kubernetes environment. 

Understood that, placing that hat file in a folder with name _UserDefined/Plugins/lil_  in integration server work directory should work, alternative to providing the absolute path location for illPath value in node.conf.yaml file. 

How to make those jar files copies into the server when deploying the bar files using manifest files? 

FYI @matthiasblomme

**Comment by trevor-dolby-at-ibm-com** [comment]
@psujeethkumar I think the `additionalJpluginDirectories` setting in server.conf.yaml should do what you need: you can put the custom node JAR files anywhere, and then add the directories containing the JAR files to the `additionalJpluginDirectories` setting.

You can also deploy the custom node JAR files in a shared library in a BAR file, and then put the name of the shared library in the `additionalJpluginDirectories` setting using the usual `{shlibname}` curly-braces reference style.

The setting is commented out in the template server.conf.yaml and should work in CP4i servers also.
