### ISSUE TITLE
Fails with "signal SIGSEGV: segmentation violation" on openshift

### ISSUE THREAD

**Issue by srikanth230486** [ot4i/ace-docker#28]
Hi,
When aceonly image is pulled from openshift using the below command, resulting in a segment violation error,

"oc new-app ibmcom/ace --env LICENSE=accept --env ACE_SERVER_NAME=acetest --env LOG_FORMAT=json"

github.com/ot4i/ace-docker/internal/**logger.(*Logger).Debugf(0x0, 0x8ea462, 0x1f, 0xc4200b7d90, 0x1, 0x1)**
--
  | /go/src/github.com/ot4i/ace-docker/internal/logger/logger.go:134 +0x26
  | main.logTermination(0xc4201f00e0, 0x1, 0x1)
  | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/logging.go:36 +0x16e
  | main.doMain(0xc4200b7f78, 0xc4200de058)
  | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:38 +0x11b
  | main.main()
  | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:147 +0x22

A nil pointer reference is being passed to 'Debugf' function.

**Comment by IBMRob** [comment]
The image hosted on ibmcom/ace is not designed or tested to be used on openshift. We would recommend using the supplied redhat based docker builds to build images that are suitable for using on RedHat Open Sift

**Comment by LeoUfimtsev** [comment]
@IBMRob Can you give a few more pointers on how to run this in Openshfit? We are running into this problem.

**Comment by IBMRob** [comment]
@LeoUfimtsev - Have you followed https://github.com/ot4i/ace-docker#red-hat-openshift-securitycontextconstraints-requirements?

**Comment by LeoUfimtsev** [comment]
Thank you very much for your response. We followed the link and we got it working with anyuidz service account:

```
oc new-project acemq
oc new-app ibmcom/ace-mq -e LICENSE=accept -e MQ_QMGR_NAME=QMGR -e ACE_SERVER_NAME=ACESERVER --name acemq
oc create serviceaccount ibmsvcaccount
oc adm policy add-scc-to-user anyuid -z ibmsvcaccount
oc patch dc/acemq --patch '{"spec":{"template":{"spec":{"serviceAccountName": "ibmsvcaccount"}}}}'
oc expose service acemq
oc get route
```
