### ISSUE TITLE
Will that disable the complete UI ?

### ISSUE THREAD

**Issue by jwende** [ot4i/ace-docker#3]
https://github.com/ot4i/ace-docker/blob/4471ff20ff5893106ccee7131f7cc98080771571/11.0.0.0/ace/ubuntu-1604/demo/Dockerfile#L12

**Comment by dcb-robinson** [comment]
Hi, you are correct. We have disabled the UI in the demo image provided.

This is a demo of how you might run the ACE v11 image in a 'cattle' like way.  We have already copied the BAR file in, unzipped it into the working directory and started the Integration Server, so wouldn't need to access the UI to perform administration tasks. Alternatively, you could leave that line out of your own image.

You could also run off the base image, which doesn't disable the UI, and then you could run in a way similar to the previous version, using the UI to administer your Integrations

**Comment by jwende** [comment]
so if you want to manage this 'cattle' you need to write your own monitoring tool to handle the runtime telemetry data ? And the admin interface would be the command line only as this disables the complete Rest API ?
J.

**Comment by dcb-robinson** [comment]
You could write your own monitoring tool, but you shouldn't have to. There are existing tools that exist you could use, e.g. Filebeat is a lightweight shipper for logs, providing a way to forward and centralize logs and files.

Ideally the application should be able to push its logs/files to a centralized service, such as ELK stack, and we are currently working towards this.

With regards to your last comment about the admin interface, you are correct.

**Comment by styblope** [comment]
>   Hi, you are correct. We have disabled the UI in the demo image provided.

Would you mind adding an explicit note in the README and in the demo Dockerfile about that? Thanks.

**Comment by IBMRob** [comment]
We no longer disable the UI in the latest version of the code. Closing this issue off now.
