### ISSUE TITLE
Docker Container on Windows Platform

### ISSUE THREAD

**Issue by amak313** [ot4i/ace-docker#30]
I can't install it using the Windows Installation, any guidance if this feature would be available soon?

**Comment by IBMRob** [comment]
Hi,

Can you explain what you mean by `I can't install it using the Windows Installation` - What are command are you running? What OS and what version of docker do you have?

**Comment by amak313** [comment]
Hello,

I have a windows host and using Docker installation on windows, I am trying to install an ACE container using the Docker commands but I couldn't find a windows installation Docker file

**Comment by IBMRob** [comment]
The docker files that we provide are only supported on a x86 based docker environment. We do not have docker files for windows containers

**Comment by lubuxnl** [comment]
Hi,
With Docker on Windows it should be possible to build Ubuntu based images of ACE using the 'docker build' commands mentioned in the README.md, e.g.

> docker build -t ace-only --build-arg ACE_INSTALL={ACE-file-in-deps-folder} --file ubuntu/Dockerfile.aceonly .

Did you already try this?

**Comment by amak313** [comment]
Hi Lubuxnl, 
I used the tar.gz version 11.0.0.3 Developer edition, its producing an error upon Handling keystore configuration

**Error processing configuration in folder keystore: /usr/local/bin/ace_config_keystore.sh: exit status 1: Error opening output file /home/aceuser/ace-server/keystore.p12 /home/aceuser/ace-server/keystore.p12: No such file or directory unable to write 'random state'**

 **[/usr/local/bin/ace_config_keystore.sh: exit status 1: Error opening output file /home/aceuser/ace-server/keystore.p12 /home/aceuser/ace-server/keystore.p12: No such file or directory unable to write 'random state']**

**Comment by amak313** [comment]
Okay it appears that the issue is with write access on the binded location on my hard drive. 
this didn't happen with ubuntu, maybe its windows security thing.
I managed to pass that error by creating a folder with name "ace-server" under the pre-created folder aceuser under binded home directory.

**Comment by lubuxnl** [comment]
Hi amak313, apparently I misunderstood your question. Glad to hear you solved it anyway ;-)
