### ISSUE TITLE
Ace overwriting ODBCSYSINI value when mqsiprofile command is run

### ISSUE THREAD

**Issue by APC02** [ot4i/ace-docker#31]
Hi,

I have set ODBCINI , ODBCSYSINI and LIBPATH environment variables during container creation in k8s cluster envand these values are set when container is created. But when I run . mqsiprofile in bin folder, the ODBCSYSINI value is getting overridden , and there are DB connection issues.
ODBCSYSINI is changing to ODBCSYSINI=/opt/ibm/ace-11/ie02/etc.

I get the below error when I run mqsicvp command.

BIP8290I: Verification passed for the ODBC environment.

BIP2393E: Database error: ODBC return code '-1' from data source ''DSN_MULEDB'' using ODBC driver manager ''/opt/ibm/ace-11/ie02/lib/libodbcinterface.so''.

Can you please check and let me know why the odbcsysini environment variable is being overwritten when I run mqsiprofile ?

[Container_Startup_ENV.txt](https://github.com/ot4i/ace-docker/files/3003909/Container_Startup_ENV.txt)
[error_log.txt](https://github.com/ot4i/ace-docker/files/3003910/error_log.txt)
[mqsicvp_error.txt](https://github.com/ot4i/ace-docker/files/3003911/mqsicvp_error.txt)
[mqsiprofile_ENV.txt](https://github.com/ot4i/ace-docker/files/3003912/mqsiprofile_ENV.txt)

**Comment by IBMRob** [comment]
@APC02. I see you have closed this issue. Did you resolve your problem?

**Comment by APC02** [comment]
Hi @IBMRob Yes I was able to resolve the issue. The InstallDir in odbcini file was changed to absolute path instead of <Your Broker install directory>.

**Comment by jayaatmakuri** [comment]
> Hi @IBMRob Yes I was able to resolve the issue. The InstallDir in odbcini file was changed to absolute path instead of .
@APC02,  iam having the exact issue.. could you please elaborate the fix you made.
