### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by lubuxnl** [ot4i/ace-docker#32]
The rhel/Dockerfile.acerhel and rhel/Dockerfile.acemqrhel files have an instruction around line 30 that copies the file LICENSE to /licenses/licensing.txt. The LICENSE is however not present in the repository, so this instruction causes the build to fail. Can you please add the proper LICENSE file?

**Comment by IBMRob** [comment]
Thanks for spotting this. Looks like we push half an update. I will get this resolved today.

**Comment by APC02** [comment]
Hi @IBMRob Do we have an update for this ?

**Comment by IBMRob** [comment]
Sorry. Slight delays in getting to this. Short term please just comment out that line from the dockerfile

**Comment by IBMRob** [comment]
The missing file has been added
