### ISSUE TITLE
Build failed: tar: ... Directory renamed before its status could be extracted

### ISSUE THREAD

**Issue by jwende** [ot4i/ace-docker#33]
My docker build (ising windows 10 docker environment) failed at the extraction of the ace file with:
tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/escodegen/node_modules/.bin: Directory renamed before its status could be extracted

I could get it running by adding --absolute-names to the tar command 

J.

**Comment by IBMRob** [comment]
This is due to a bug in the MacOS file system I suspect. If you follow https://github.com/docker/hub-feedback/issues/727#issuecomment-299533372 it should hopefully fix it.

**Comment by sidagf** [comment]
@IBMRob Is there a reason the solution @jwende suggested has not been included in the repository?

jwende's suggestion of --absolute-names worked great for Debian 9 running in Hyper-V.

**Comment by IBMRob** [comment]
@sidagf - The extra option has not been fully tested in all our configurations. This repo is a mirror of what we use to produce multiple different packages so we don't update it until its been fully tested and gone through a review cycle.

**Comment by IBMRob** [comment]
This has now been resolved by https://github.com/ot4i/ace-docker/pull/42
