### ISSUE TITLE
Image not working on OpenShift when pulled from Quay repository

### ISSUE THREAD

**Issue by ajiteshshukladeloitte** [ot4i/ace-docker#36]
Hi Team,
we built the new image by using the shell script available at Docker Hub (provided by IBM) and the IBM ACE tar (downloaded from IBM official passport portal) on RHEL server (v7)with the required accesses. The built image is getting deployed successfully and working fine with docker on local machine and the RHEL server(where image was built). However when we tried to deploy the same image on OpenShift, we are getting the below error. We discussed about this issue with OpenShift folks and they suggested us to follow the IBM documentation to deploy the image on OpenShift. Does IBM have any documentation to deploy the built ACE image on OpenShift ?
RHEL version was 7.6 on the server in which we built the image. 
openshift repository(Quay) the image passed with zero Vulnerabilities, from where we deployed the image.
Rhel tar used from passport :-IBM_ACE_11.0.0.4_LNX_X8664_INCTKT.tar
RHEL specific scripts were used to built the image.
https://github.com/ot4i/ace-docker/blob/master/rhel/Dockerfile.acerhel
Log :-
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6af5b6]

goroutine 1 [running]:
github.com/ot4i/ace-docker/internal/logger.(*Logger).Debugf(0x0, 0x8ea498, 0x1f, 0xc42006dd90, 0x1, 0x1)
	/go/src/github.com/ot4i/ace-docker/internal/logger/logger.go:134 +0x26
main.logTermination(0xc42009d090, 0x1, 0x1)
	/go/src/github.com/ot4i/ace-docker/cmd/runaceserver/logging.go:36 +0x16e
main.doMain(0xc42006df78, 0xc4200341d8)
	/go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:38 +0x11b
main.main()
/go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:147 +0x22

**Comment by ajiteshshukladeloitte** [comment]
Hi Team,
We were able to resolve the issue, it was with SCC issue.
Earlier we were using restricted SCC.
After changing it to anyuid SCC ACE Pod came up.

We tried ibm-ace-scc SCC as well, but same issue happened and POD didn't came up.
ibm-ace-scc information is present at:- https://github.com/ot4i/ace-helm/blob/master/ibm-ace/README.md

Using anyuid might give security concern, please help us by provide ace specific IBM recommended SCC.

Thanks
Ajitesh

**Comment by IBMRob** [comment]
We have updated the documentation to now match what we use in ICP which is the ibm-anyuid-scc. This should enable the image to run on RedHat Open Shift.

https://github.com/ot4i/ace-helm/blob/master/ibm-ace/README.md#red-hat-openshift-securitycontextconstraints-requirements

If you have further issues once you have configured the ibm-anyuid-scc please re-open this issue

**Comment by atulsingh0** [comment]
> Hi Team,
> We were able to resolve the issue, it was with SCC issue.
> Earlier we were using restricted SCC.
> After changing it to anyuid SCC ACE Pod came up.
> 
> We tried ibm-ace-scc SCC as well, but same issue happened and POD didn't came up.
> ibm-ace-scc information is present at:- https://github.com/ot4i/ace-helm/blob/master/ibm-ace/README.md
> 
> Using anyuid might give security concern, please help us by provide ace specific IBM recommended SCC.
> 
> Thanks
> Ajitesh

Hi Ajitesh,
I am also facing the same issue, can you please guide me what exactly you have done to fix this?
