### ISSUE TITLE
ACE Container Build Error

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#37]
We are getting below error when building ace-only container from Linux 64 image on MacBook Kindly help - 

Command - ./build-rhel.sh ace-only ace11 11.0.0.3-ACE-LINUX64-DEVELOP.tar.gz

Error -

> Step 20/39 : RUN tar xzf $ACE_INSTALL --exclude ace-11.\*/tools --strip-components 1 --directory /opt/ibm/ace-11
>  ---> Running in 07bbc5d333ab
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/nyc/node_modules/.bin: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/nyc/node_modules: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/nyc: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/stryker-javascript-mutator/node_modules/.bin: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/stryker-javascript-mutator/node_modules: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/stryker-javascript-mutator: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/.bin: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/eslint/node_modules/.bin: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/eslint/node_modules: Directory renamed before its status could be extracted
> tar: server/nodejs/lib/node_modules/ace-admin-server/node_modules/eslint: Directory renamed before its status could be extracted
> tar: Exiting with failure status due to previous errors
> The command '/bin/sh -c tar xzf $ACE_INSTALL --exclude ace-11.\*/tools --strip-components 1 --directory /opt/ibm/ace-11' returned a non-zero code: 2
> C02WGAHVHTD

**Comment by IBMRob** [comment]
@atulsingh0 - FYI - To build the Redhat images you need to run the build on a machine which is licensed to pull all the Redhat files. Normally this is a red-hot machine. I am not aware of it being possible on a non Redhat based machine.

The error your seeing is due to a bug in the linux filesystem. Can you try adding "--absolute-names" to the tar command

**Comment by atulsingh0** [comment]
Thanks @IBMRob, this fixed the issue.
