### ISSUE TITLE
What will be the value of MQ base Image

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#38]
Hi There,
I am trying to build a ace-mq container but confused with 4th parameter, what should I pass in {MQ_Base_Image_Name}

I am running below command which is keep failing....

./build-rhel.sh ace-mq ace11 11.0.0.4-ACE-LINUX64-DEVELOP.tar.gz ibmcom/ace-mq

**Comment by IBMRob** [comment]
The 4th parameter is the MQ container image tag to build on top of. There is no shipped developer edition of MQ on Red-hot so you can either build it using the MQ instructions or downloaded it from [IBM Passport Advantage] (https://www.ibm.com/software/passportadvantage/).

**Comment by atulsingh0** [comment]
Thanks, What I have done is - I've pulled the MQ base image as - docker pull ibmcom/mq and now trying to rebuilt the ace-mq image with below commands - 

> $ docker images
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> ace/builder         11.0.0.4            6a1cb6fbe648        4 days ago          3.21GB
> ibmcom/mq           latest              53bef00f4486        2 weeks ago         896MB

now building as - 
> ./build-rhel.sh ace-mq ace11 11.0.0.4-ACE-LINUX64-DEVELOP.tar.gz ibmcom/mq

This build is failing at a step where docker file instruction is trying to alter the container file - 

Step 4/22 : RUN sed -i 's/# minlen = 9/minlen = 9/'  /etc/security/pwquality.conf &&     sed -i 's/PASS_MIN_DAYS\t0/PASS_MIN_DAYS\t1/'  /etc/login.defs &&     sed -i 's/PASS_MAX_DAYS\t99999/PASS_MAX_DAYS\t90/'  /etc/login.defs
 ---> Running in 0bb08c922223
sed: can't read /etc/security/pwquality.conf: No such file or directory
The command '/bin/sh -c sed -i 's/# minlen = 9/minlen = 9/'  /etc/security/pwquality.conf &&     sed -i 's/PASS_MIN_DAYS\t0/PASS_MIN_DAYS\t1/'  /etc/login.defs &&     sed -i 's/PASS_MAX_DAYS\t99999/PASS_MAX_DAYS\t90/'  /etc/login.defs' returned a non-zero code: 2

**Comment by IBMRob** [comment]
You can't use the rhel build scripts with non-redhat images. If you want to use the MQ images from docker hub please use the ubuntu docker file at https://github.com/ot4i/ace-docker/blob/master/ubuntu/Dockerfile.acemq

**Comment by atulsingh0** [comment]
So Rob, In that case, I can not create an RHEL ACE image with Ubuntu MQ image as this will also get failed with the above error?

**Comment by IBMRob** [comment]
@atulsingh0 - That is correct. You can only build a RHEL based image if you build on top of the RHEL based MQ image. If you want to use an Ubuntu MQ image then you should be building the ubuntu based ACE image.

**Comment by atulsingh0** [comment]
Hi @IBMRob 
Now, my build is failing with below error - 

Step 16/18 : COPY ./deps/$ACE_INSTALL .
Error processing tar file(exit status 1): write /IBM_ACE_V11.0.0.3_F_RHEL_ICP_RHOS.tar.gz: no space left on device

Though I have put these binaries under /app folder on my server and it has 138G of free space.

**Comment by IBMRob** [comment]
@atulsingh0 - You have run out of space in your docker filesystem. You need to look at the docker configuration on your system and see where its storing its file. The filesystem will have run out of space. 

As your original issue is resolved I am closing this issue. For anything different please open a new issue
