### ISSUE TITLE
Build an image with App Connect Enterprise and MQ Client RHEL SCRIPT

### ISSUE THREAD

**Issue by ajiteshshukladeloitte** [ot4i/ace-docker#43]
Hi Team,

Please help us by providing the RHEL script for Ace with MQ client, currently we have the one for ubuntu.

We tried to run the ubuntu script but getting file or directory not found error.
Base ace image is a rhel image which is working in openshift environment
Script used :
docker build -t acewithmqclient:latest --build-arg BASE_IMAGE=acewithmqclient:latest -f /home/centos/ace-docker-master/ubuntu/Dockerfile.acemqclient /home/centos/ace-docker-master/ubuntu/
Error 
COPY failed: stat /var/lib/docker/tmp/docker-builder032326740/home/centos/ace-docker-master/ubuntu/installMQClient.sh: no such file or directory

Thanks
Ajitesh

**Comment by IBMRob** [comment]
@ajiteshshukladeloitte - Currently we do not have a dockerfile for adding the MQ client to a red-hat based image. 

I suggest you look at the code for the ubuntu platform and amend it accordingly to support the Red Hat binaries.

In the future we are looking to move to a UBI based image. When we do this it will include a MQ client option.
