### ISSUE TITLE
ACE Image is not working in Openshift

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#45]
Hi there, 
ACE image is working fine in local docker engine but throwing below error when uploaded into Openshift? Can you please guide how can I resolve this issue? 
1. Openshift Admin team is not allowing us to modify the SCC
2. Openshift is triggering Image with non root user 

> panic: runtime error: invalid memory address or nil pointer dereference
> --
>   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6af5b6]
>   |  
>   | goroutine 1 [running]:
>   | github.com/ot4i/ace-docker/internal/logger.(*Logger).Debugf(0x0, 0x8ea498, 0x1f, 0xc4200edd90, 0x1, 0x1)
>   | /go/src/github.com/ot4i/ace-docker/internal/logger/logger.go:134 +0x26
>   | main.logTermination(0xc4200d60f0, 0x1, 0x1)
>   | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/logging.go:36 +0x16e
>   | main.doMain(0xc4200edf78, 0xc42010c058)
>   | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:38 +0x11b
>   | main.main()
>   | /go/src/github.com/ot4i/ace-docker/cmd/runaceserver/main.go:147 +0x22
> 
>

**Comment by IBMRob** [comment]
@atulsingh0 - As per our documentation. Our charts are designed to be run using the `ibm-anyuid-scc` / `ibm-privileged-scc` SCCs. They will not work with the default SCCs.
