### ISSUE TITLE
Unable to build the sample ACE only image

### ISSUE THREAD

**Issue by thomascychan** [ot4i/ace-docker#51]
I successfully built the ACE production (v.11.0.0.4) only image using Ubuntu as the OS, so I've the ace-only image in docker.  However, when I tried to build the sample based on the ACE only image, I got ACE's exceptions as shown below.  In the "sample/Dockerfile.aceonly" it has the following command. I don't recall the "bars" folder is actually created in the ace-only image. Could this be the problem?

`COPY bars_aceonly /home/aceuser/bars`

> [docker@reg2lxap0034 sample]$ docker build -t aceapp --file Dockerfile.aceonly .
Sending build context to Docker daemon  175.6kB
Step 1/3 : FROM ace-only:latest
 ---> 97832429ecaf
Step 2/3 : COPY bars_aceonly /home/aceuser/bars
 ---> 345f1e4b7af9
Step 3/3 : RUN ace_compile_bars.sh
 ---> Running in b9ee6955e322
BIP2114E: IBM App Connect Enterprise internal error: diagnostic information ''Failed to read ZIP file - could not navigate to first file'', ''/home/aceuser/bars/CallHTTPSEcho.bar'', '1208', '-102'.
An internal software error has occurred in IBM App Connect Enterprise.  Further messages may indicate the effect of this error on the component.
Shutdown and restart the component.  If the problem continues to occur, then restart the system.  If the problem still continues to occur contact your IBM support center.

>BIP8081E: An error occurred while processing the command.
An error occurred while the command was running; the command has cleaned up and ended.
Use messages prior to this one to determine the cause of the error.
 Check for some common problems:
 Does the user id have the correct authorities (for example a member of the mqbrkrs group)?
 Is any operating system limit set too low to allow the command to run?
 Is the environment correctly set up?
 Correct the problem and retry the command, otherwise, contact your IBM support center.
>BIP2114E: IBM App Connect Enterprise internal error: diagnostic information ''Failed to read ZIP file - could not navigate to first file'', ''/home/aceuser/bars/HTTPSEcho.bar'', '1208', '-102'.
An internal software error has occurred in IBM App Connect Enterprise.  Further messages may indicate the effect of this error on the component.
Shutdown and restart the component.  If the problem continues to occur, then restart the system.  If the problem still continues to occur contact your IBM support center.

>BIP8081E: An error occurred while processing the command.
An error occurred while the command was running; the command has cleaned up and ended.
Use messages prior to this one to determine the cause of the error.
 Check for some common problems:
 Does the user id have the correct authorities (for example a member of the mqbrkrs group)?
 Is any operating system limit set too low to allow the command to run?
 Is the environment correctly set up?
 Correct the problem and retry the command, otherwise, contact your IBM support center.
The command '/bin/sh -c ace_compile_bars.sh' returned a non-zero code: 81

**Comment by atulsingh0** [comment]
Use "ADD" to add bars, it will create the folder if not exists.
