### ISSUE TITLE
configuring database for IBM ACE 11.0.0.4 within Openshift

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#55]
Hi,

I am running ACE 11.0.0.4 in openshift and I am trying to configure database. I have placed odbc.ini file in sample/initial-config/odbcini/ and setdbparams file in sample/initial-config/setdbparms/ folder . and build an app image. Now where should i place  the fiels in server and how it will configure the DB connection in container. Need some clarity on same.If we have any detail step how to configure DB it will be very helpful.

**Comment by IBMRob** [comment]
@har2103 - When you say "where should i place the fiels in server" - what files are you referring to?

" how it will configure the DB connection in container." - Which aspects of configuring the connection are you referring to? The supplied odbcini will be configured for the IntegrationServer and the supplied username and password will also be setup.

**Comment by har2103** [comment]
i was referring the odbc.ini and setdbparams.txt file. as state above i have provided the configuration file in initial_config dir under odbc and setdbparams folders now i want to know how it will pick the db deatils also how can i verify my db connection.

**Comment by IBMRob** [comment]
The integration server will automatically be configured with the files on startup. You can now deploy the flow which makes use of the connections

**Comment by har2103** [comment]
is there any mqsiverifiction command to check if my db id and password is successfully configured to Integration Server?

**Comment by har2103** [comment]
Also i can see some update happened yesterday on sample/setdbparams/setdbparam.txt

mqsisetdbparms -w /home/aceuser/ace-server -n salesforce::SecurityIdentity -u myUsername -p myPassword -c myClientID -s myClientSecret


so i have to update my file with above command with details and how it will run this command?

also once its run how will check if it ran successfuly?

**Comment by IBMRob** [comment]
If you look at the logs on startup you see see that it reports that it ran the command successfully. 

The only way to check on the running broker would be to exec into the container and then run the commands like on a standard linux machine.

**Comment by har2103** [comment]
2019-07-15T14:30:19.552Z Error processing configuration in folder setdbparms: fork/exec /usr/local/bin/ace_config_setdbparms.sh: exec format error
--
  | 2019-07-15T14:30:19.553Z [fork/exec /usr/local/bin/ace_config_setdbparms.sh: exec format error]

i am getting this error while starting the IS and its getting shutdown.

# resource user password
setdbparms::resource user password
mqsisetdbparms -w /home/aceuser/ace-server -n resource -u username -p password

i am using above format in my setdbparam.txt and replaced the actual values to resource , user and password.

please help me how to resolve this.

also mqsisetdbparms command is supported to 11.0.0.4 ibm ace version. i am using ace 11.0.0.4

**Comment by har2103** [comment]
any update on my above query?

**Comment by IBMRob** [comment]
Can you provide your full logs including the docker run command. 
Note that the new format command is not supported in the prebuilt images. This is only in the master branch and has not been included in a release so you need to build the image yourself to be able to use the new format setdbparam.txt file

**Comment by har2103** [comment]
so i built my new base image with ace verion 11.0.04 with old ace-docker and update setdbparams.sh script with new(which recently got changed)  and also updated setdbparams.txt file in initial-config. now when am running my ace server in opneshift pod my INTEGRATION SERVER is not connecting to Database and it says invalid account details. though i have provided correct user name ans password.

sh-4.2$ mqsicvp -n <> -u <> -p <>
BIP8290I: Verification passed for the ODBC environment.

BIP2393E: Database error: ODBC return code '-1' from data source ''HUB'' using ODBC driver manager ''/opt/ibm/ace-11/ie02/lib/libodbcinterface.so''.
The integration node received an error when processing a database operation. The ODBC return code was '-1'. See the following messages for information obtained from the database about this error.
Use the following messages to determine the cause of the error. Typical problems are an incorrect data source, or table names. Correct either the database or the integration node configuration. Usethe mqsicvp command to test connectivity to this database.
BIP2322E: Database error: SQL State ''46''; Native Error Code '1017'; Error Text ''[unixODBC][IBM][ODBC 20101 driver][20101]ORA-01017: invalid username/password; logon denied''.
The error has the following diagnostic information:     SQL State             ''46''     SQL Native Error Code '1017'     SQL Error Text        ''[unixODBC][IBM][ODBC 20101 driver][20101]ORA-01017:invalid username/password; logon denied''
This message may be accompanied by other messages describing the effect on the integration node itself. Use the reason identified in this message with the accompanying messages to determine the cause of the error. Use the mqsicvp command to test connectivity to this database.

BIP8040E: Unable to connect to the database.
The database cannot be accessed with the specified user Id and password pair.
- Check that the database is running.
 - Check that the database has an adequate number of database connections available for use.
 - On Windows, check that an ODBC connection has been created.
 - On systems that use $ODBCINI, check that the file pointed to by $ODBCINI has been correctly updated.
 - On z/OS check the BIPDSNAO member of the component's dataset, and check the DB2 64bit ODBC driver (DSNAO64C) is in the STEPLIB.
 - Use mqsisetdbparms to set the password to the correct value and try again.

**Comment by jayaatmakuri** [comment]
HI @har2103 , how you resolved this issue. iam also getting the same error when i gave mqsicvp. kindly help

**Comment by curious937285e** [comment]
I am also facing the same issue. Can you help me with the resolution?
