### ISSUE TITLE
Additional identifiers to mqsisetdbparms

### ISSUE THREAD

**Issue by JaneEH** [ot4i/ace-docker#58]
Hi,

i'm trying to set up a Salesforce Security Identity with ace -docker. The problem is that Salesforse want's several identifiers and at the moment you provide just -u <userId> -p <password>. Can you be so kind add few additional identifiers? 

Example: 
salesforce::SecurityIdentity -u $USER -p $PASSWORD -c $CLIENT_ID -s $CLIENT_SECRET

mqsisetdbparms ${ACE_SERVER_NAME} -n <resource> -u <userId> -p <password>
resource1 user1 password1
resource2 user2 password2

**Comment by IBMRob** [comment]
Hi @JaneEH,

This something we are looking at add although its not at the top of our priority at the moment.We are looking to add a new option where by you could also provide the full mqsisetdbparms command i.e. we would support a file with the following

```
smtp::RobsIdentity myUsername myPassword
mqsisetdbparms salesforce::SecurityIdentity -u myUsername -p myPassword -c myClientID -s myClientSecret
```

You are perfectly welcome to fork this repo and make the updates to the files and provide us with a PR with updates to support both the old format and the new format.

**Comment by IBMRob** [comment]
Was simple enough to do in the end :) - https://github.com/ot4i/ace-docker/pull/60

**Comment by JaneEH** [comment]
Wow, awsome! Thank you very much!
