### ISSUE TITLE
The "/var/mqm" folder was removed in the MQ Client install

### ISSUE THREAD

**Issue by thomascychan** [ot4i/ace-docker#59]
After I built the ACE production only v11.0.0.5 with ubi and then with the MQ Client, I noticed that the "/var/mqm" folder was instructed to be removed in the "ubi/install-mq.sh". This doesn't allow me to edit the "/var/mqm/mqclient.ini" file to create a CertificateLabel. And I wasn't able to run the "dspmqver" command to confirm the installation. I commented out that line in the script and rebuilt the image. I'm just wondering if the removal of the "/var/mqm" folder was done intentionally or not.

**Comment by IBMRob** [comment]
We delete this directory as per the MQ Samples seen at https://github.com/ibm-messaging/mq-container/blob/master/install-mq.sh#L72

**Comment by thomascychan** [comment]
I also built the MQ image last week, and I agree with you the install-mq.sh script does delete the "/var/mqm" folder because the project prefers using the "/mnt/mqm/data" which is correctly linked for you under "/var/mqm" at runtime. You can see the symbolic link below.

[https://github.com/ibm-messaging/mq-container/blob/dc00231ec1eb928ce12a0b742c98837dbbbfcd24/install-mq.sh#L87](url)

**Comment by IBMRob** [comment]
Resolved by https://github.com/ot4i/ace-docker/pull/73
