### ISSUE TITLE
rhel folder is missing with related Docker files.

### ISSUE THREAD

**Issue by PrashantKaraganvi** [ot4i/ace-docker#62]
Hello,

I am building ace-mq container on RHEL but i see in the latest update , rhel related docker files are missing. Could you please let me know when those will be added.

And I see ACE and MQ images are mostly using Ubuntu as base image, does this mean, RHEL is not supported for these things?

**Comment by mattbaileyuk** [comment]
Hello

There is no RHEL folder, but also no Ubuntu one as we rebased on Red Hat's Universal Base Image (UBI), which is itself based on RHEL but can be pulled in to use for free for containers. We want to build on just this base image going forward.

I believe MQ have also done the same with their own images (and we build on their UBI image for our ACE+MQ one)

**Comment by IBMRob** [comment]
Closing as @mattbaileyuk mentiontions we are no longer providing RHEL based images.

**Comment by PrashantKaraganvi** [comment]
Thanks for the information @mattbaileyuk
