### ISSUE TITLE
Pulling 11.0.0.5 image

### ISSUE THREAD

**Issue by jussisoiluva** [ot4i/ace-docker#63]
Hi,
I'm trying to pull the newest ACE image with "docker pull ibmcom/ace:11.0.0.5", but it gives me the "Error response from daemon: manifest for ibmcom/ace:11.0.0.5 not found" error.

I have pulled the ibmcom/ace:latest but it would nice to use the actual version tag to keep up with the versions.

Thank you!

**Comment by IBMRob** [comment]
Specific versions are also available. This release we have also appended the architecture to allow for further platforms to be added in the future

https://hub.docker.com/r/ibmcom/ace/tags
