### ISSUE TITLE
Unable to run microdnf through a corporate proxy

### ISSUE THREAD

**Issue by LukeDaigneault** [ot4i/ace-docker#66]
I am attempting to build the ace only docker image in a virtual machine running ubuntu 18.04 Server

I have a NAT network adapter and can access the external internet via the corporate proxy. I set the proxy on the VM and on the /etc/systemd/system/snap.docker.dockerd.service file.

This allows me to run docker build and pull the base images. However while running the build it calls microdnf from the minimal-ubi image. This is failing with the following message.

`(microdnf:6): libdnf-WARNING **: 13:44:05.047: Skipping refresh of ubi-7: cannot update repo 'ubi-7': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/os/repodata/repomd.xml [Resolving timed out after 30000 milliseconds]`

I have searched but can find no way to provide to microdnf the proxy server.

Any guidance on this would be appreciated,

**Comment by IBMRob** [comment]
Hi,

Unfortunately we don't have any extra guidance on supporting proxies when running in VMs/Docker

**Comment by LukeDaigneault** [comment]
For anyone searching for the solution to this you must pass the proxy in the build arguments.

example that worked for me

` docker build --build-arg https_proxy=http://myproxy.proxy:port -t ace-only --build-arg ACE_INSTALL=IBM_ACE_11.0.0.5.tar.gz  --file ubi/Dockerfile.aceonly .`

It seems that docker loads those into the environment of all the images in during the build.
