### ISSUE TITLE
/bin/sh: microdnf: command not found The command '/bin/sh -c microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all' returned a non-zero code: 127

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#67]
hi,

i am creating base image for ace & mq with 11.0.0.5 and am getting below error.

Step 27/42 : RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all
 ---> Running in 0c920c3bfb70
/bin/sh: microdnf: command not found
The command '/bin/sh -c microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all' returned a non-zero code: 127
[root@localhost ace-docker]# 

so i want to understand how can i resolve this error.

**Comment by mattbaileyuk** [comment]
Are you building from the Dockerfile in this repo without changes? `microdnf` should be including the base image, and we haven't run into this problem with our own builds.

**Comment by LukeDaigneault** [comment]
I have seen this you have to make sure you are using the UBI image of MQ from docker hub. This is not the one tagged as latest.

**Comment by har2103** [comment]
> problem

Thanks. yes my base image doesnt have this package.

**Comment by har2103** [comment]
> I have seen this you have to make sure you are using the UBI image of MQ from docker hub. This is not the one tagged as latest.

I need to build for RHEL server. but i got the issue. thanks for reply.

**Comment by VinayakaBS** [comment]
Hi All, 
We are facing the same issue in the same step, 
The below command is used for building the image,
 docker build -t ace-mq --build-arg BASE_IMAGE=ibmcom/mq --build-arg ACE_INSTALL=ace-11.0.0.5.tar.gz --file ubi/Dockerfile.acemq .

We are new to this topic , could you please provide steps to resolve the issue.

Thanks
Vinayaka

**Comment by IBMRob** [comment]
@VinayakaBS Please open a new issue referencing this one. Please also read the comments above regarding the version of ibmcom/mq you are using

**Comment by VinayakaBS** [comment]
Thanks Rob..I will do the same

**Comment by mikepedroza** [comment]
I think you need to be running as root; you may be running as the default user.. (this is what caused it for me )   so I think it would be something like:

USER root
RUN microdnf install ...
USER 1001
