### ISSUE TITLE
ace_config_initial-config.sh is missing

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#68]
When I have tried to initialize my ACE image, docker gave me below error - 

```
2019-07-19T17:17:27.437Z Processing configuration in folder initial-config
2019-07-19T17:17:27.437Z Error processing configuration in folder initial-config: exec: "ace_config_initial-config.sh": executable file not found in $PATH
2019-07-19T17:17:27.437Z [exec: "ace_config_initial-config.sh": executable file not found in $PATH]
2019-07-19T17:17:27.437Z Stopping Integration Server
```

I did not find "ace_config_initial-config.sh" in github as well

**Comment by IBMRob** [comment]
Hi @atulsingh0 

That looks like you have created a folder called "initial-config" inside the initial-config directory. The way the startup scripts work is they scan the folder /home/ace/initial-config for all folders and for each folder it looks for a script called `ace_config_<folder-name>.sh`

**Comment by atulsingh0** [comment]
Thanks @IBMRob , yes I did the same mistake. One more query here -- can we point /home/aceuser/ace-server data to host directory as we did for initial-config

**Comment by IBMRob** [comment]
You could but we would not recommend it. The design around the initial-config and loading up everything you need on startup means that the data in the ace-server directory is stateless essentially. If you restarted a container with an ace-server that already had loaded the config it may result in some failures when attempting to reconfigure it depending on what your doing (i.e. certain policies might fail to re-deploy etc)

**Comment by atulsingh0** [comment]
I agree second time I don't want to configure again so will not mount the directory on /home/ace/initial-config. 
When I have tried to mount the both, I got the below error 

Command Args:
```
sudo docker run --name ace-mq-oc1 -p 7630:7600 -p 7620:7610 -p 7830:7800 -p 7820:7810 -p 7873:7843 -p 1444:1414 \
-p 8828:8818 --mount type=bind,src=/app/initial-config,dst=/home/aceuser/initial-config \
--mount type=bind,src=/app/acedata/ace-server,dst=/home/aceuser/ace-server \
--env LICENSE=accept --env MQ_QMGR_NAME=QM1 --env ACE_SERVER_NAME=ACE-SERVER --detach ace-mq-oc
```


> 
> 2019-07-19T18:05:28.951Z Error processing configuration in folder setdbparms: /usr/local/bin/ace_config_setdbparms.sh: exit status 127: BIP8383E: The directory specified, '/home/aceuser/ace-server', does not exist or is not an integration server work directory. Ensure the directory exists and is initialized for use as an integration server work directory.
> 2019-07-19T18:05:28.951Z [/usr/local/bin/ace_config_setdbparms.sh: exit status 127: BIP8383E: The directory specified, '/home/aceuser/ace-server', does not exist or is not an integration server work directory. Ensure the directory exists and is initialized for use as an integration server work directory.]
