### ISSUE TITLE
/bin/sh: microdnf: command not found The command '/bin/sh -c microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all' returned a non-zero code: 127...#68

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#70]
Hi All,
We are facing the same issue in the same step,

Step 27/42 : RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all

The below command is used for building the image,
docker build -t ace-mq --build-arg BASE_IMAGE=ibmcom/mq --build-arg ACE_INSTALL=ace-11.0.0.5.tar.gz --file ubi/Dockerfile.acemq .

We are new to this topic , could you please provide steps to resolve the issue.
Thanks
Vinayaka

**Comment by IBMRob** [comment]
Can you validate you are pulling in the latest version go ibmcom/mq which is UBI based. If you have an older version than the latest it will not be UBI based and thus be missing `microdnf`

**Comment by VinayakaBS** [comment]
Thanks a lot Rob, Now could able to build the ace-mq image ,

can you please validate the below command used
 docker build -t ace-mq --build-arg BASE_IMAGE=ibmcom/mq --build-arg ACE_INSTALL=ace-11.0.0.5.tar.gz --file ubi/Dockerfile.acemq .


Also Step27, has some warnings and Installation (null)

Step 27/42 : RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all
 ---> Running in 7a02608dc2e4

(process:6): librhsm-WARNING **: 13:42:32.857: Found 0 entitlement certificates

(process:6): librhsm-WARNING **: 13:42:32.868: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Transaction: 6 packages
python-libs-2.7.5-80.el7_6.x86_64 (ubi-7)
openssl-1:1.0.2k-16.el7_6.1.x86_64 (ubi-7)
python-2.7.5-80.el7_6.x86_64 (ubi-7)
gdbm-1.10-8.el7.x86_64 (ubi-7)
unzip-6.0-19.el7.x86_64 (ubi-7)
make-1:3.82-23.el7.x86_64 (ubi-7)
Downloading packages...
Running transaction test...
Installing: make;1:3.82-23.el7;x86_64;ubi-7
Installing: gdbm;1.10-8.el7;x86_64;ubi-7
Installing: python-libs;2.7.5-80.el7_6;x86_64;ubi-7
Installing: (null)
Installing: python;2.7.5-80.el7_6;x86_64;ubi-7
Installing: (null)
Installing: openssl;1:1.0.2k-16.el7_6.1;x86_64;ubi-7
Installing: (null)
Installing: unzip;6.0-19.el7;x86_64;ubi-7
Installing: (null)
Complete.

(process:54): librhsm-WARNING **: 13:42:57.781: Found 0 entitlement certificates

(process:54): librhsm-WARNING **: 13:42:57.784: Found 0 entitlement certificates
Complete.
Removing intermediate container 7a02608dc2e4
 ---> a9ab2b89c70a



Can you please say whether we can ignore the above warnings and also please validate the docker build command BASE IMAGE is correct or not.

Thanks
Vinayaka

**Comment by IBMRob** [comment]
Those warnings can be ignored. The base image is what ever your building from. It will take the file that is in your local docker repo called that image. Ideally in this scenario it will pull it directly from docker hub

**Comment by VinayakaBS** [comment]
Thanks Rob, your points really helped us to learn

**Comment by VinayakaBS** [comment]
PS C:\ACEPROD\ace-docker-master\ace-docker-master> docker exec -it ae263e6808d5 bash
bash-4.2$ su - aceuser
su: user aceuser does not exist


I created container , when  tried to switch user it throws "aceuser does not exist", 
by default is in aceuser ?

Thanks
Vinayaka

**Comment by mattbaileyuk** [comment]
@VinayakaBS In the ACE+MQ image the user is `mqm` rather than `aceuser` (so it has permissions for MQ which switched away from using `root` in 9.1.2 which the latest `Dockerfile` now users)

**Comment by VinayakaBS** [comment]
Thanks Matt for the clarification
