### ISSUE TITLE
Step 27/42 : RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#72]
Team,
Yesterday we could build the image , but today at the same step we are getting error,

Command used:
docker build -t ace-mq --build-arg BASE_IMAGE=ibmcom/mq --build-arg ACE_INSTALL=ace-11.0.0.5.tar.gz --file ubi/Dockerfile.acemq .

Error:

Step 27/42 : RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all
 ---> Running in b2c44e0ae394

(process:6): librhsm-WARNING **: 13:13:26.433: Found 0 entitlement certificates

(process:6): librhsm-WARNING **: 13:13:26.452: Found 0 entitlement certificates
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 13:13:28.947: Skipping refresh of ubi-7: cannot update repo 'ubi-7': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (35): SSL connect error for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/os/repodata/repomd.xml [Encountered end of file]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 13:13:29.803: Skipping refresh of ubi-7-optional: cannot update repo 'ubi-7-optional': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (35): SSL connect error for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/optional/os/repodata/repomd.xml [Encountered end of file]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 13:13:30.756: Skipping refresh of ubi-7-rhah: cannot update repo 'ubi-7-rhah': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (35): SSL connect error for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/atomic/7/7Server/x86_64/os/repodata/repomd.xml [Encountered end of file]
Downloading metadata...

(microdnf:6): libdnf-WARNING **: 13:13:31.862: Skipping refresh of ubi-7-rhscl: cannot update repo 'ubi-7-rhscl': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (35): SSL connect error for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi/server/7/7Server/x86_64/rhscl/1/os/repodata/repomd.xml [Encountered end of file]
error: No package matches 'openssl'
The command '/bin/sh -c microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all' returned a non-zero code: 1

Can you please help to proceed further

Thanks

**Comment by mattbaileyuk** [comment]
That looks like the machine you are building on is having trouble reaching RedHat's UDN in order for `microdnf` to install packages. I have just done a build of the images here on our systems and they were able to proceed fine, so please check the network connectivity (it could also have been a problem with RedHat's servers they were having earlier, but I think it falls over to mirrors so I'd surprised if they were all down too).

**Comment by VinayakaBS** [comment]
Thanks Matt. You are correct , it is due to network connectivity issue.Once connected with the other network , the image steps got completed.

Thank you
