### ISSUE TITLE
Password for mqm user, inside the docker container

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#75]
Hi Team
We are trying to install SFTP inside the container we created, we used the command "sudo apt-get sftp", but mqm user asking for password

PS C:\ACEJul30\ace-docker-master\ace-docker-master> docker exec -it 4d2cdd7d12ff bash
bash-4.2$ sudo apt-get sftp

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.

[sudo] password for mqm:
bash-4.2$

Kindly let us know the password for mqm.

Thanks

**Comment by IBMRob** [comment]
Although sudo was previously installed it was never configured in the image. As a result it can’t be used. In our recent images sudo is no longer installed
If you need to perform actions as root you will need to do it via an extra Dockerfile where you switch to the root user and perform the required commands

**Comment by VinayakaBS** [comment]
Thanks Rob for the reply

apt-get sftp; apt-get command is not found

We are trying to install SFTP inside the docker container , is there any way with the existing image and its container ?

Thanks

**Comment by IBMRob** [comment]
Its not possible because the user your running as is doesn't have root authority. The only way is by using the Dockerfile and switching users. 

Note the images are also now running ubi so you need to use the `microdnf install` command to install packages.

**Comment by VinayakaBS** [comment]
Hi Rob,

Can you please help me on scripts which need to be added in the existing docker file.

Thanks
Vinayaka

**Comment by IBMRob** [comment]
You need to 
* create a docker file which builds on top of the ACE image
* switch to the root user
* use microdnf to install the sftp package (you will need to check what its called in the redhat catalog
* switch back to the appropriate user for the image your building on top of (aceuser or mqm)

**Comment by IBMRob** [comment]
Closing due to lack of feedback
