### ISSUE TITLE
unable to build ACE-MQ image

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#78]
Hi ,

I am building an ACE+MQ Image and it exit at below step. want to understand what is the reason it is exiting.

Step 10/24 : RUN /opt/ibm/ace-11/ace make registry global accept license silently
 ---> Running in d800db0d9667
You do not have permission to accept the license. See your system administrator to obtain write permissions to the IBM App Connect Enterprise installation directory.
The command '/bin/sh -c /opt/ibm/ace-11/ace make registry global accept license silently' returned a non-zero code: 1

Appreciate your response.

**Comment by IBMRob** [comment]
Can you please provide the full output from your build including the command you are running
