### ISSUE TITLE
Unable to build ace-base

### ISSUE THREAD

**Issue by pijpe00** [ot4i/ace-docker#8]
Hello,

when I want to build the ace-base ( cd 11.0.0.0/ace/ubuntu-1604/base
docker build -t ace:11.0.0.0 .) I get the following error:

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/lib/snapd/void/Dockerfile: no such file or directory

How can I solve this?

**Comment by JakesIV** [comment]
it does not seem like there is allot of help from IBM on the issues logged.

**Comment by jwende** [comment]
Looks like a Docker environment problem imho. Please check if you can build any other docker image.
J.

**Comment by pijpe00** [comment]
problem solved. I made some changements in the dockerfile
