### ISSUE TITLE
Additional Scripts for Installing SFTP-Not Working

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#80]
Team

We are trying to Install SFTP(apt-get install sftp) inside the container,
As advised previously, We are trying to add the additional scripts in the existing docker file to make SFTP get installed inside the container.

But the below script options doesn't work ,
We added the below scripts and tried building the image,

Option1:
RUN apt-get update && apt-get -y install sftp server
Error: Package not found

Option2:
RUN yum update -y && yum install -y openssh-clients
Error: Yum not found

option3:
RUN microdnf install openssh-server

Can you please provide the correct script to add in the existing docker file and also Step number to add the same , We are new to docker scripts.

Thanks

**Comment by IBMRob** [comment]
@VinayakaBS - If your using the latest version of the dockerfile you need to use microdnf for installs because the image is based on ubi-minimal

**Comment by VinayakaBS** [comment]
Thanks for your reply.

We tried executing the microdnf commands inside the container, got the below error

bash-4.2$ microdnf install sftp
error: Failed to create: /var/cache/yum/metadata
bash-4.2$ microdnf install sftp server
error: Failed to create: /var/cache/yum/metadata

(or ) We need to include inside the docker file ?

Thanks

**Comment by IBMRob** [comment]
It needs to be done as part of a docker file where the user is currently set to root. The user the container runs as doesn't have permissions to install applications.

**Comment by VinayakaBS** [comment]
Thanks Rob , We will check and will update you

**Comment by VinayakaBS** [comment]
Hi Rob

PF the details,
**1) Docker Build Command:**

docker build -t ace-mq --build-arg BASE_IMAGE=ibmcom/mq --build-arg ACE_INSTALL=ace-11.0.0.5.tar.gz --file ubi/Dockerfile.acemq .

**2) New line added for sftp:**

RUN microdnf install sftp

3) Error:

Step 30/43 : RUN microdnf install sftp
 ---> Running in 0ab53e972858

(microdnf:1): librhsm-WARNING **: 08:02:23.816: Found 0 entitlement certificates

(microdnf:1): librhsm-WARNING **: 08:02:23.827: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
error: No package matches 'sftp'
The command '/bin/sh -c microdnf install sftp' returned a non-zero code: 1





4)Full docker file:

ARG BASE_IMAGE=ibmcom/mq:9.1.2.0-UBI-amd64

FROM golang:1.10.3 as builder

WORKDIR /go/src/github.com/ot4i/ace-docker/
ARG IMAGE_REVISION="Not specified"
ARG IMAGE_SOURCE="Not specified"
COPY cmd/ ./cmd
COPY internal/ ./internal
COPY vendor/ ./vendor
RUN go build -ldflags "-X \"main.ImageCreated=$(date --iso-8601=seconds)\" -X \"main.ImageRevision=$IMAGE_REVISION\" -X \"main.ImageSource=$IMAGE_SOURCE\"" ./cmd/runaceserver/
RUN go build ./cmd/chkaceready/
RUN go build ./cmd/chkacehealthy/
# Run all unit tests
RUN go test -v ./cmd/runaceserver/
RUN go test -v ./internal/...
RUN go vet ./cmd/... ./internal/...

ARG ACE_INSTALL=ace-11.0.0.2.tar.gz
WORKDIR /opt/ibm
COPY deps/$ACE_INSTALL .
RUN mkdir ace-11
RUN tar xzf $ACE_INSTALL --absolute-names --exclude ace-11.\*/tools --strip-components 1 --directory /opt/ibm/ace-11

FROM $BASE_IMAGE

ENV SUMMARY="Integration Server for App Connect Enterprise" \
    DESCRIPTION="Integration Server for App Connect Enterprise" \
    PRODNAME="AppConnectEnterprise" \
    COMPNAME="IntegrationServer"

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Integration Server for App Connect Enterprise" \
      io.openshift.tags="$PRODNAME,$COMPNAME" \
      com.redhat.component="$PRODNAME-$COMPNAME" \
      name="$PRODNAME/$COMPNAME" \
      vendor="IBM" \
      version="11.0.0.4" \
      release="1" \
      license="IBM" \
      maintainer="Hybrid Integration Platform Cloud" \
      io.openshift.expose-services="" \
      usage=""

USER root

# Add required license as text file in Liceses directory (GPL, MIT, APACHE, Partner End User Agreement, etc)
COPY /licenses/ /licenses/
COPY LICENSE /licenses/licensing.txt

WORKDIR /opt/ibm

RUN microdnf install --nodocs openssl util-linux unzip python2 && microdnf clean all
COPY --from=builder /opt/ibm/ace-11 /opt/ibm/ace-11
RUN /opt/ibm/ace-11/ace make registry global accept license silently

#New line added for sftp
RUN microdnf install sftp


# Copy in PID1 process
COPY --from=builder /go/src/github.com/ot4i/ace-docker/runaceserver /usr/local/bin/
COPY --from=builder /go/src/github.com/ot4i/ace-docker/chkace* /usr/local/bin/

# Copy in script files
COPY *.sh /usr/local/bin/

ADD https://storage.googleapis.com/kubernetes-release/release/v1.12.9/bin/linux/amd64/kubectl /usr/local/bin/kubectl
RUN chmod +x /usr/local/bin/kubectl && \
    /usr/local/bin/kubectl version --client

# Create the ace workdir for user mqm, and chmod script files
RUN mkdir /home/aceuser \
  && chown mqm:mqm /home/aceuser \
  && usermod -a -G mqbrkrs mqm \
  && usermod -d /home/aceuser mqm \
  && su - mqm -c '. /opt/ibm/ace-11/server/bin/mqsiprofile && mqsicreateworkdir /home/aceuser/ace-server' \
  && chmod 755 /usr/local/bin/*

# Set BASH_ENV to source mqsiprofile when using docker exec bash -c
ENV BASH_ENV=/usr/local/bin/ace_env.sh

# Expose ports.  7600, 7800, 7843 for ACE; 1414 for MQ; 9157 for MQ metrics; 9483 for ACE metrics;
EXPOSE 7600 7800 7843 1414 9157 9483

USER mqm

WORKDIR /home/aceuser
RUN mkdir /home/aceuser/initial-config && chown mqm:mqm /home/aceuser/initial-config

ENV USE_QMGR=true LOG_FORMAT=basic

# Set entrypoint to run management script
ENTRYPOINT ["runaceserver"]


Thanks
Vinayaka

**Comment by IBMRob** [comment]
The error is that the package can be found. Looking at the redhat repos it looks like its a package called "openssh-clients-7.4p1" that provides sftp so that is the one you will need to install

**Comment by VinayakaBS** [comment]
Thanks Rob ,

We will check with this package and let you know.

**Comment by VinayakaBS** [comment]
Hi Rob

Thank you, We included the below line in the docker file, We are able to connect with SFTP

RUN microdnf install openssh-clients-7.4p1

Thanks

**Comment by atulsingh0** [comment]
@VinayakaBS how are you using sftp as you need to do SSH setup between pods and target system and our pods are keep changing based on deployments

**Comment by VinayakaBS** [comment]
HI Atul 
For now we configured the SFTP properties at the File node level. As Rob mentioned "RUN microdnf install openssh-clients-7.4p1" is the script to be included in the docker file.

Thanks
