### ISSUE TITLE
Order of initial-config script execution 

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#82]
Hi Rob,
Is there any order of initial-config script execution ?? I want to add a script which will execute all the mqsichangeproperties command for our code but this should be done after "bar deployment". What if any command throws an error?

**Comment by IBMRob** [comment]
@atulsingh0 - We don't have an ordering of the scripts. They get processed in the order detected by this code - https://github.com/ot4i/ace-docker/blob/0c194235dd31eee4275f2887d870879c8b17c04f/cmd/runaceserver/integrationserver.go#L90
