### ISSUE TITLE
Dockerfile.mqclient file: install-mq.sh and install-mq-client.prereqs.sh paths are incorrect

### ISSUE THREAD

**Issue by awasthan** [ot4i/ace-docker#83]
Below statements need to be updated. 
COPY install-mq.sh /usr/local/bin/
COPY install-mq-client-prereqs.sh /usr/local/bin/

These should be changed to
COPY ubi/install-mq.sh /usr/local/bin/
COPY ubi/install-mq-client-prereqs.sh /usr/local/bin/

**Comment by IBMRob** [comment]
@awasthan - I don't agree, if you follow the documented instructions the dockerfile works as expected - https://github.com/ot4i/ace-docker#build-an-image-with-app-connect-enterprise-and-mq-client

**Comment by awasthan** [comment]
@IBMRob I followed the documented steps and got below error. After correcting the path, it worked. 

 ---> Using cache
 ---> a68fd1bfa006
Step 39/39 : ENTRYPOINT ["runaceserver"]
 ---> Using cache
 ---> c7595d4497bd
Successfully built c7595d4497bd
Successfully tagged ace-only:latest
+ docker build -t ace-mqclient --build-arg BASE_IMAGE=ace-only --file ubi/Dockerfile.mqclient .
Sending build context to Docker daemon   1.36GB

Step 1/12 : ARG BASE_IMAGE=ibmcom/ace
Step 2/12 : FROM $BASE_IMAGE
 ---> c7595d4497bd
Step 3/12 : ARG MQ_URL="https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev912_linux_x86-64.tar.gz"
 ---> Using cache
 ---> 5a0a14ed77fa
Step 4/12 : ARG MQ_URL_USER
 ---> Using cache
 ---> 385ec8a3d0bc
Step 5/12 : ARG MQ_URL_PASS
 ---> Using cache
 ---> 7f5f9ca139f8
Step 6/12 : ARG MQ_PACKAGES="MQSeriesRuntime*.rpm MQSeriesJava*.rpm MQSeriesGSKit*.rpm MQSeriesClient*.rpm"
 ---> Using cache
 ---> 36554a9f222d
Step 7/12 : ARG MQM_UID=888
 ---> Using cache
 ---> f5be180d2cd6
Step 8/12 : USER root
 ---> Using cache
 ---> e4f873dd7edb
Step 9/12 : COPY install-mq.sh /usr/local/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder086648343/install-mq.sh: no such file or directory
Build step 'Execute shell' marked build as failure
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE

-----------------------------------------------------------------------------
After updating the path, it goes through, however I don't understand why its pulling MQ image. It should add only MQ client libraries, which should be quick. It takes enormous time. Below is the output snippet after updating the path.
 ---> a68fd1bfa006
Step 39/39 : ENTRYPOINT ["runaceserver"]
 ---> Using cache
 ---> c7595d4497bd
Successfully built c7595d4497bd
Successfully tagged ace-only:latest
+ docker build -t ace-mqclient --build-arg BASE_IMAGE=ace-only --file ubi/Dockerfile.mqclient .
Sending build context to Docker daemon   1.36GB

Step 1/12 : ARG BASE_IMAGE=ibmcom/ace
Step 2/12 : FROM $BASE_IMAGE
 ---> c7595d4497bd
Step 3/12 : ARG MQ_URL="https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev912_linux_x86-64.tar.gz"
 ---> Using cache
 ---> 5a0a14ed77fa
Step 4/12 : ARG MQ_URL_USER
 ---> Using cache
 ---> 385ec8a3d0bc
Step 5/12 : ARG MQ_URL_PASS
 ---> Using cache
 ---> 7f5f9ca139f8
Step 6/12 : ARG MQ_PACKAGES="MQSeriesRuntime*.rpm MQSeriesJava*.rpm MQSeriesGSKit*.rpm MQSeriesClient*.rpm"
 ---> Using cache
 ---> 36554a9f222d
Step 7/12 : ARG MQM_UID=888
 ---> Using cache
 ---> f5be180d2cd6
Step 8/12 : USER root
 ---> Using cache
 ---> e4f873dd7edb
Step 9/12 : COPY ubi/install-mq.sh /usr/local/bin/
 ---> 530505f666c6
Step 10/12 : COPY ubi/install-mq-client-prereqs.sh /usr/local/bin/
 ---> bfd18cd99974
Step 11/12 : RUN chmod u+x /usr/local/bin/install-*.sh   && sleep 1   && install-mq-client-prereqs.sh $MQM_UID   && install-mq.sh $MQM_UID
 ---> Running in 9658583c5c9b
[91m+ test -f /usr/bin/microdnf
+ MICRODNF=true
+ test -f /usr/bin/rpm
+ RPM=true
+ true
[0m[91m+ EXTRA_RPMS='ca-certificates curl tar'
+ true
+ microdnf install --nodocs ca-certificates curl tar
[0m[91m
(process:16): librhsm-WARNING **: 10:44:28.068: Found 0 entitlement certificates

(process:16): librhsm-WARNING **: 10:44:28.072: Found 0 entitlement certificates
[0mDownloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Nothing to do.
[91m+ true
+ microdnf clean all
[0m[91m
(process:74): librhsm-WARNING **: 10:44:52.828: Found 0 entitlement certificates
[0m[91m
(process:74): librhsm-WARNING **: 10:44:52.830: Found 0 entitlement certificates
[0mComplete.
[91m+ mqm_uid=888
+ test -f /usr/bin/microdnf
+ MICRODNF=true
+ test -f /usr/bin/rpm
+ RPM=true
+ DIR_EXTRACT=/tmp/mq
+ mkdir -p /tmp/mq
[0m[91m+ cd /tmp/mq
+ '[' -z '' ']'
+ curl -LO https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev912_linux_x86-64.tar.gz
[0m[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   T[0m[91motal   Spent    Left  Speed

**Comment by IBMRob** [comment]
Currently we use the MQ Server download to obtain all the required client libraries to install. This is based on a modification of the existing MQ Server install code.

**Comment by awasthan** [comment]
@IBMRob I see that it's installing MQ runtime. Why so?


[91m+ true
+ cd /tmp/mq/MQServer
[0m[91m+ rpm -ivh **MQSeriesRuntime-9.1.2-0.x86_64.rpm** MQSeriesJava-9.1.2-0.x86_64.rpm MQSeriesGSKit-9.1.2-0.x86_64.rpm MQSeriesClient-9.1.2-0.x86_64.rpm
[0mPreparing...                          ########################################
Updating / installing...
MQSeriesRuntime-9.1.2-0               ########################################
MQSeriesJava-9.1.2-0                  ########################################
MQSeriesGSKit-9.1.2-0                 ########################################
MQSeriesClient-9.1.2-0                ########################################
[91m+ find /opt/mqm -name '*.tar.gz' -delete
[0m[91m+ rm -rf /tmp/mq
[0m[91m+ rm -rf /var/mqm

**Comment by IBMRob** [comment]
As per the MQ Docs the runtime is required by the client - https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.ins.doc/q115250_.htm

**Comment by awasthan** [comment]
Oh, my apologies... I confused MQ Series runtime with MQ Server package.
However I think downloading the full MQ package only for client installation is killing.

**Comment by IBMRob** [comment]
We are open to PRs that can make it more efficient :)

**Comment by IBMRob** [comment]
Closing as working as designed
