### ISSUE TITLE
ACE docker startup

### ISSUE THREAD

**Issue by jehuty11** [ot4i/ace-docker#86]
Hello, 

When I restart my ACE docker, already run with Initial-config folder mounted (like in your sample page) with docker command, I have this error : 
BIP2832E: The web user account 'userAce' cannot be created because the account already exists.

To restart my container, I must stop, delete and launch the docker run command. 

Do you have an idea to solve this ? 

Regards,
J.

**Comment by IBMRob** [comment]
Hi @jehuty11 - At the moment the sample images are designed to be used in an Openshift (Kubernetes) environment, as a result it presumes that when it starts up it has to initialise all the configuration each time it starts up. 

To work around the issue you could modify the config scripts to support checking if the configuration has already been processed and skip it where appropriate.

**Comment by IBMRob** [comment]
Closing as no response.
