### ISSUE TITLE
ace_config_policy to provision for monitoring profiles

### ISSUE THREAD

**Issue by xkennawb** [ot4i/ace-docker#87]
**Issue:** ace_config_policy to provision for monitoring profiles (suffix monprofile.xml)

IBM’s documentation for policies and the use of monitoring profiles specifies “The XML file must have an extension of .monprofile.xml and must be contained in a policy project”.  This does not work as ace_config_policy.sh does not cater for monitoring profile suffix monprofile.xml

Can the following please be added to ace_config_policy.sh:

if ls /home/aceuser/initial-config/policy/*.monprofile.xml >/dev/null 2>&1; then
  for policyfile in `ls /home/aceuser/initial-config/policy/*.monprofile.xml`; do
    if [ -s "${policyfile}" ]; then
      cp "${policyfile}" /home/aceuser/ace-server/overrides/DefaultPolicies/.
    fi
  done
fi

**Comment by IBMRob** [comment]
Hi @xkennawb,

We are aware of this limitation and is on our backlog. We hope to be resolving it soon.

**Comment by IBMRob** [comment]
This repo has been updated to provide a new ACE image. If you think this issue is still applicable please re-open. 

For general ACE enquiries please use  https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?communitykey=77544459-9fda-40da-ae0b-fc8c76f0ce18
