### ISSUE TITLE
Installing git,ant and cron plugins

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#88]
Team

We included the below scripts at the beginning of the Docker file to install ant,cron and git plugins 

Included in the Second Line of the docker file ,

FROM ubuntu:14.04
RUN apt-get update && apt-get install -y \
  bzr \
  cvs \
  git \
  ant \
  cron \
  mercurial \
  subversion

The docker file got successfully executed. We are able to create the container as well.

But inside the container , the command for git,ant are not getting executed or shows command not found.

Could you please review and guide us to install the git , ant and cron.

Thanks

**Comment by IBMRob** [comment]
This repo is specifically for App Connect Enterprise containers. The question above looks to be a generic docker question. Please direct this at the docker community for assistance.
