### ISSUE TITLE
Problems with MQ Libraries

### ISSUE THREAD

**Issue by hugoarjona23** [ot4i/ace-docker#9]
Im deployed the bar application on ace-server and trying to start msgflow with MQ Nodes, 
but generate this exception: 

```
2018-09-18 15:22:46.859400: [Thread 24] (Msg 1/2) BIP9320E: Message Flow 'test', 'test' encountered a failure and could not start.
2018-09-18 15:22:46.859464: [Thread 24] (Msg 2/2) BIP2684E: A component was configured to use WebSphere MQ, but the required MQ libraries are not available.
--

How can I configure these MQ libraries to start the msgflow of my application?

**Comment by IBMRob** [comment]
To run MQ nodes you need to have the MQ libraries available. The v11.0.0.0 did not include any MQ libraries. If you want to use MQ you can now use the new 11.0.0.2 Dockerfile.acemq file.

**Comment by Myhappyapps** [comment]
Please tell sir how to connect MQ libraries in ACE in Mac

**Comment by mattbaileyuk** [comment]
This issue has been closed for nearly two years, and I don't believe it is the same problem (the original issue was related to the lack of MQ node support in 11.0.0.0), so please open another issue detailing what problem you are running into, and what Dockerfile you are using.
