### ISSUE TITLE
Change mqsimode for image to non-production

### ISSUE THREAD

**Issue by anilskymint** [ot4i/ace-docker#90]
Hi,

How do we change the image mqsimode to non-production ? Right now, we see only dev and production image modes.

Regards,
Anil

**Comment by IBMRob** [comment]
Hi

We don't have a mechanism for changing the mqsimode. If you want to change the mode of an image you will need to extend the docker image, run mqsiprofile and then the mqsimode command with the appropriate parameters.

**Comment by anilskymint** [comment]
Hi,

We are not able to run mqsimode as aceuser. Can the mode only be changed as root user ?

Regards,
Anil

**Comment by IBMRob** [comment]
In the current image because the install binaries are owned by root you are unable to change the mqsimode as aceuser, you need to switch to the root user to be able to switch the mode.

We'll look to see if we can switch the install to be done as aceuser which should then allow the command by aceuser

**Comment by anilskymint** [comment]
Hi Rob,

I tried changing the mode using Dockerfile, but was unsuccessful. Since runace server is the entrypoint, I think the integration server is starting in advanced mode only. 

USER root
RUN /opt/ibm/ace-11/server/bin/mqsimode -o nonproduction
USER aceuser

Can you please let me know if switching the install binaries to aceuser is being checked ?

Thanks,
Anil

**Comment by IBMRob** [comment]
When you build the docker file what is the output? Does the command succeed? You might need to run the mqsiprofile first before the mqsimode to load the appropriate environment.

**Comment by anilskymint** [comment]
Hi Rob,

**Dockerfile :**
FROM 2d8b3054b0fe
USER root
RUN . /opt/ibm/ace-11/server/bin/mqsiprofile
CMD ["/opt/ibm/ace-11/server/bin/mqsimode","-o","nonproduction"
USER aceuser

**docker build -t ace-1411 .**
Sending build context to Docker daemon  3.533GB
Step 1/5 : FROM 2d8b3054b0fe
 ---> 2d8b3054b0fe
Step 2/5 : USER root
 ---> Using cache
 ---> 1a9fa1f6c18d
Step 3/5 : RUN . /opt/ibm/ace-11/server/bin/mqsiprofile
 ---> Using cache
 ---> d3ec073e234d
Step 4/5 : CMD ["/opt/ibm/ace-11/server/bin/mqsimode","-o","nonproduction"
 ---> Running in 0de75c56b345
Removing intermediate container 0de75c56b345
 ---> a15d6564bd20
Step 5/5 : USER aceuser
 ---> Running in 40a7e14d2a3a
Removing intermediate container 40a7e14d2a3a
 ---> 98a044123ad0
Successfully built 98a044123ad0
Successfully tagged ace-1411:latest

**Container Output :**

docker run --detach --name aceserver -p 7600:7600 -p 7800:7800 -p 7843:7843 --env LICENSE=accept --env ACE_SERVER_NAME=ACESERVER 98a044123ad0
d7192a3c3bde9e186ac9d11f54f41280e48bc7915520db37c8c8a74ca71ef484
[root@vm014475 ace-11.0.0.5]# docker exec -ti aceserver /bin/bash
[aceuser@d7192a3c3bde ~]$ id
uid=2222(aceuser) gid=2222(aceuser) groups=2222(aceuser),10(wheel),1000(mqbrkrs)
[aceuser@d7192a3c3bde ~]$ . /opt/ibm/ace-11/server/bin/mqsiprofile

MQSI 11.0.0.5
/opt/ibm/ace-11/server

[aceuser@d7192a3c3bde ~]$ mqsimode
BIP1802I: This IBM App Connect Enterprise runtime installation is in 'advanced' mode.
BIP8071I: Successful command completion.
[aceuser@d7192a3c3bde ~]$ exit

The mode is still advanced mode only.
