### ISSUE TITLE
Enable debug port in ACE-MQ Image on Openshift

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#94]
I have given the the debug port in server.yaml file and expose this port as a node port on Openshift, but unable to enable debug port on ACE toolkit, whenever trying to enable the port on integration server, it wait for some time and then throws timeout error.

**Comment by IBMRob** [comment]
Hi,

Please can you provide some more information i.e. 
* server.yaml you have used to set the debug port
* output logs from the IntegrationServer
* yaml output of the service you have updated
* URL you are providing to the toolkit to enable connectivity

**Comment by IBMRob** [comment]
Closing due to lack of response
