### ISSUE TITLE
Licensed IIB -ace tar file - SFTP issue

### ISSUE THREAD

**Issue by VinayakaBS** [ot4i/ace-docker#95]
Team

We are building the Docker file with the image build with Licensed software .

As instructed earlier we included "RUN microdnf install openssh-clients-7.4p1" in the docker file and done the build. 

But SFTP is not working. Could you guide us to resolve the issue.

Thanks
Vinayaka

**Comment by IBMRob** [comment]
Hi,

Can you provide a bit more information on what does not work? What are you trying to do? What doesn't work, What error messages? Given that this is a custom build please provide your docker file.

**Comment by VinayakaBS** [comment]
We constructed the image via docker load command

docker image load -i ibm-ace-mq-server-prod_11.0.0.5.1-amd64.tar.gz

In the above created image , SFTP command not found, So we used docker file to add SFTP property,

docker build -t newacemq --build-arg BASE_IMAGE=ibm-ace-mq-server-prod:11.0.0.5.1-amd64 --file ubi/Dockerfile.acemq .

Docker file content:---------

ARG BASE_IMAGE=ibm-ace-mq-server-prod:11.0.0.5.1-amd64

#New lines added
FROM ubuntu:14.04
FROM golang:1.10.3 as builder


#FROM golang:1.10.3 as builder


RUN microdnf install openssh-clients-7.4p1

-------------------------

Build Result:
--------------------
Sending build context to Docker daemon   2.65GB
Step 1/4 : ARG BASE_IMAGE=ibm-ace-mq-server-prod:11.0.0.5.1-amd64
Step 2/4 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
a7344f52cb74: Pull complete                                                                                                                                                                  515c9bb51536: Pull complete                                                                                                                                                                  e1eabe0537eb: Pull complete                                                                                                                                                                  4701f1215c13: Pull complete                                                                                                                                                                  Digest: sha256:2f7c79927b346e436cc14c92bd4e5bd778c3bd7037f35bc639ac1589a7acfa90
Status: Downloaded newer image for ubuntu:14.04
 ---> 2c5e00d77a67
Step 3/4 : FROM golang:1.10.3 as builder
1.10.3: Pulling from library/golang
55cbf04beb70: Pull complete                                                                                                                                                                  1607093a898c: Pull complete                                                                                                                                                                  9a8ea045c926: Pull complete                                                                                                                                                                  d4eee24d4dac: Pull complete                                                                                                                                                                  9c35c9787a2f: Pull complete                                                                                                                                                                  6a66653f6388: Pull complete                                                                                                                                                                  102f6b19f797: Pull complete                                                                                                                                                                  Digest: sha256:3c54fa85d6262d2ef7695ee2f8793f1f4f9809ce4a08ca2e213235ef4cfdcb66
Status: Downloaded newer image for golang:1.10.3
 ---> d0e7a411e3da
Step 4/4 : RUN microdnf install openssh-clients-7.4p1
 ---> Running in df19a2fb9404
/bin/sh: 1: microdnf: not found
The command '/bin/sh -c microdnf install openssh-clients-7.4p1' returned a non-zero code: 127

--------------------------------------------------------


Thanks

**Comment by IBMRob** [comment]
The docker file above is never going to work as your building on top of golang:1.10.3.

You need a dockerfile similar to 
```
FROM ibm-ace-mq-server-prod:11.0.0.5.1-amd64
USER root
RUN  microdnf install openssh-clients-7.4p1
USER aceuser
```
and then build it using 

`docker build -t ace-sftp:11.0.0.5.1 -f ./NewDockerfile .`

**Comment by VinayakaBS** [comment]
Hi Rob 

Thanks

We will check and update you.

**Comment by VinayakaBS** [comment]
Hi Rob

PF the build result 

Sending build context to Docker daemon  11.78kB
Step 1/4 : FROM ibm-ace-mq-server-prod:11.0.0.5.1-amd64
 ---> ef4b6270cfb9
Step 2/4 : USER root
 ---> Running in eaab9859af50
Removing intermediate container eaab9859af50
 ---> 9d120298d147
Step 3/4 : RUN  microdnf install openssh-clients-7.4p1
 ---> Running in 1d5abbf883f6

(microdnf:1): librhsm-WARNING **: 07:14:38.165: Found 0 entitlement certificates

(microdnf:1): librhsm-WARNING **: 07:14:38.176: Found 0 entitlement certificates
Downloading metadata...

(microdnf:1): libdnf-WARNING **: 07:14:46.358: Skipping refresh of ubi-7: cannot move /var/cache/yum/metadata/ubi-7-7Server-x86_64/packages to /var/cache/yum/metadata/ubi-7-7Server-x86_64.tmp/packages
Downloading metadata...
Downloading metadata...

(microdnf:1): libdnf-WARNING **: 07:14:57.649: Skipping refresh of ubi-7-rhah: cannot move /var/cache/yum/metadata/ubi-7-rhah-7Server-x86_64/packages to /var/cache/yum/metadata/ubi-7-rhah-7Server-x86_64.tmp/packages
Downloading metadata...
error: No package matches 'openssh-clients-7.4p1'
The command '/bin/sh -c microdnf install openssh-clients-7.4p1' returned a non-zero code: 1

Can you please check, it fails at the last step.

Thanks

**Comment by IBMRob** [comment]
Note the version of the package may change. You need to check what the latest version of the package is.

**Comment by sawantkaustubh20** [comment]
Hi Team,

How can we configure SFTP and SMTP Server on CP4I Integration Server without using Commands because when pod will restarts those commands need to be run automatically, if anyone can guide it will be helpful.
