### ISSUE TITLE
How to check if mqm password changed?

### ISSUE THREAD

**Issue by atulsingh0** [ot4i/ace-docker#97]
I am following this docker file (https://github.com/ot4i/ace-docker/blob/master/sample/Dockerfile.acemq) to alter the password for mqm and newly added user 'mqadm', But not sure if the password is changed. 

When trying to connect MQ QM from MQ explorer without password, it got connect in read-only mode but when trying to use mqm password, it says user (mqm and mqadm) are not have enough privilege to connect as admin.

**Comment by IBMRob** [comment]
This repo no longer supports embedded MQ Server
