### ISSUE TITLE
Public key authentication not working using RSA

### ISSUE THREAD

**Issue by mikkolaakko** [ot4i/ace-docker#98]
I am trying to send a file to a remote SFTP server. I can connect to the server using ssh and my public rsa key. However, this does not work in ACE using a File Output node. The error I see on the remove server is:
> Received disconnect from 172.17.0.1 port 59912:3: com.jcraft.jsch.JSchException: Auth fail [preauth]

The error in ACE userTrace is:
> Reason: 'publickey authentication credentials invalid'.

File Output node works with public key authentication when I used ECDSA. 

Is it possible to get RSA to work with File Output node?

**Comment by IBMRob** [comment]
Please use the IBM developer forums for generic ACE support questions https://community.ibm.com/community/user/integration/communities/community-home/digestviewer?tab=digestviewer&CommunityKey=77544459-9fda-40da-ae0b-fc8c76f0ce18
