### ISSUE TITLE
Sample packages do not compile BAR files

### ISSUE THREAD

**Issue by cullenlinn** [ot4i/ace-docker#99]
When building images using the sample items (Dockerfile.acemq, Dockerfile.aceonly) any included BAR files are not actually compiled as expected. Instead, they are compiled only once the container is started. I believe that this is rooted in the fact that the /ace_compile_bars.sh file does not include the "-c" option to the 'mqsibar' command.

**Comment by tdolby-at-uk-ibm-com** [comment]
@cullenlinn Thank you for raising this - should be merged now.
